### ISSUE TITLE
basic configuration 

### ISSUE THREAD

**Issue by nrahuf** [linuxserver/docker-calibre-web#107]
hi 

i am hoping someone can help 

i have tried to create docker image using CLI on a qnap NAS. The image loads and starts. soon as i click the web link - the basic configuration page opens up and asks me to enter the library location. although i have added the correct folder path in the CLI command when creating the docker. 

if i try and save the location of libary - get an error which says DB location not found. tried putting in the folder path everyway i can think of and still get an error.

any ideas?

**Comment by j0nnymoe** [comment]
"Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an **existing** Calibre database."
You need to provide a database for this to use.

**Comment by nrahuf** [comment]
I have added the path to the metadata.db file but still comes up with an error DB location not valid please enter correct path. 

have added path /share/etc etc /metadata.db. 

This is in the same folder of the books. 

If i open calibre on the desktop it finds the data base etc - so not sure where i am going wrong

**Comment by nrahuf** [comment]
sorry just realised i havent been following the instructions - total idiot!!!
