### ISSUE TITLE
no close button when you read EPUB book

### ISSUE THREAD

**Issue by schel4ok** [linuxserver/docker-calibre-web#109]
When open EPUB book card it is possible to read directly in browser, but there is no close button when you read it.
I checked in Chrome browser on android mobile phone and in Chrome browser on laptop.

**Comment by CHBMB** [comment]
Sounds like an upstream issue rather than a peculiarity of the docker container.

**Comment by schel4ok** [comment]
you mean that it should be addressed to calibre developper?

**Comment by j0nnymoe** [comment]
To the calibre-web developer, yea.

**Comment by CHBMB** [comment]
Closing this as it's an upstream feature request not a bug.
