### ISSUE TITLE
DB Location is not Valid, Please Enter Correct Path -> metadata.db exists and seems in correct place

### ISSUE THREAD

**Issue by mildfuzz** [linuxserver/docker-calibre-web#110]
Sorry, this might be in the wrong place.

Trying to set up CalibreWeb using [DockStarter](https://dockstarter.com/). The image installs fine, but I get `DB Location is not Valid, Please Enter Correct Path`

I have checked the location of `metadata.db` and it exists, I used it in a previous install but not sure why it would have issue here. 

```
root@DockSTARTer:/# ls -lah /books/metadata.db
-rwxrwxrwx 1 abc abc 9.1M Jul 30 04:52 /books/metadata.db
```

**Comment by aptalca** [comment]
Did you enter /books as the library path in the setup wizard?

**Comment by nassoor** [comment]
I don't know if this will help, but I just tore my hair out trying to fix this until I noticed that I flipped the PGID and PUID numbers 😁

**Comment by mildfuzz** [comment]
> Did you enter /books as the library path in the setup wizard?

damn, this was it 🤦‍♂️

TY
