### ISSUE TITLE
Utilizing robots.txt

### ISSUE THREAD

**Issue by alfonsrv** [linuxserver/docker-calibre-web#112]
In the release notes I can see `Added route to robots.txt` but the documentation doesn't state on where to put it nor comes with a default `robots.txt`.

**Comment by tobbenb** [comment]
That is from the upstream release notes, so you will have to ask them.

**Comment by alfonsrv** [comment]
https://github.com/janeczku/calibre-web/wiki/Extend-Features#use-your-own-robotstxt-file
