### ISSUE TITLE
On Raspberry Pi: crash-loop on startup with 'Fatal Python error: pyinit_main: can't initialize time'

### ISSUE THREAD

**Issue by BernhardGehl** [linuxserver/docker-calibre-web#119]
## Expected Behaviour
calibre-web starting
## Current Behaviour
container starts but calibre-web gets locked in a loop of "pyinit_main: can't initialize time'
## Steps to Reproduce
1. start calibre-web container from docker-compose on Raspberry Pi cluster IN the swarm or OUTSIDE the swarm (same behavior)
## Environment
OS: Raspbian Buster
CPU architecture: armhf
How docker service was installed: Docker repo (other linuxserver images working)
## Command used to create docker container
copy from docker-compose:

> version: "3.2"
> services:
>  ebooks_kids:
> image: ghcr.io/linuxserver/calibre-web
>     restart: unless-stopped
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=Europe/Berlin
>     volumes:
> #      - config_calibreweb_kids:/config
>       - /served/volumes/calibre_config_calibreweb_kids:/config
>       - /served/eLiterature/kids:/books
>     ports:
>       - 8083:8083
>     deploy:
>       replicas: 1
>       restart_policy:
>         condition: on-failure
>         max_attempts: 5
>       placement:
>         constraints:
>           - "node.role==worker"
## Docker logs
(excerpt - it's looping)

> ebooks_kids_1  | [cont-init.d] 99-custom-scripts: executing... 
> ebooks_kids_1  | [custom-init] no custom files found exiting...
> ebooks_kids_1  | [cont-init.d] 99-custom-scripts: exited 0.
> ebooks_kids_1  | [cont-init.d] done.
> ebooks_kids_1  | [services.d] starting services
> ebooks_kids_1  | [services.d] done.
> ebooks_kids_1  | Fatal Python error: pyinit_main: can't initialize time
> ebooks_kids_1  | Python runtime state: core initialized
> ebooks_kids_1  | PermissionError: [Errno 1] Operation not permitted
> ebooks_kids_1  | 
> ebooks_kids_1  | Current thread 0xb6f57460 (most recent call first):
> ebooks_kids_1  | <no Python frame>
> ebooks_kids_1  | Fatal Python error: pyinit_main: can't initialize time
> ebooks_kids_1  | Python runtime state: core initialized
> ebooks_kids_1  | PermissionError: [Errno 1] Operation not permitted
> ebooks_kids_1  | 
> ebooks_kids_1  | Current thread 0xb6fcd460 (most recent call first):
> ebooks_kids_1  | <no Python frame>

## Story Mode
I'm running calibre-web on a ebooks_kids_1  | [cont-init.d] 30-config: exited 0.
small cluster of Raspberry Pis (4x RPi3, 1x RPi4). When I set it up some time ago, it worked fine but recently (I can't pin it down to an image update, sorry), the server fails to start up properly. Instead it keeps looping:

> ebooks_kids_1  | Current thread 0xb6fc2460 (most recent call first):
> ebooks_kids_1  | <no Python frame>
> ebooks_kids_1  | Fatal Python error: pyinit_main: can't initialize time
> ebooks_kids_1  | Python runtime state: core initialized
> ebooks_kids_1  | PermissionError: [Errno 1] Operation not permitted

* First I thought, I'd screwed up the permissions of my config - but they seem to be fine. To make sure, I tested with a blank new docker volume and I got the same error message.
* I tested the same on my /books mount but no change
* Then I found a similar issue on Github for another linuxserver image: https://github.com/linuxserver/docker-papermerge/issues/4
* I messed with a version of the Dockerfile, but failed trying to add the libseccomp2 binary with some permissions errors

Could someone with more docker know-how maybe look at this?

**Comment by Roxedus** [comment]
As noted in the readme, this image got rebased to focal. Check out this link https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal-and-alpine-3-13

**Comment by BernhardGehl** [comment]
> As noted in the readme, this image got rebased to focal. Check out this link https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal-and-alpine-3-13

Thanks! I didn't get it that I had to update the _host_ OS!

Sorry for bothering you...

**Comment by HarvsG** [comment]
I Installed the updated version

```
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
```

But had no luck

I had to use 'run --privileged'  - or rather toggled the 'privileged mode' in portainer.
