### ISSUE TITLE
cant read in browser

### ISSUE THREAD

**Issue by mkarikom** [linuxserver/docker-calibre-web#121]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

it's missing the "read in browser" button in every single book.

------------------------------

## Expected Behavior
books contain "read in browser button"
https://imgur.com/zO4qMuP

## Current Behavior
books are missing "read in browser" button
https://imgur.com/NxU8OS3

## Steps to Reproduce

1. install the container with the docker compose from linuxserver docs
2. select an existing library in the initial config screen
3. open one of the books

## Environment
**OS:** ubuntu 20.04
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
official docker repo

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /mnt/md0/insshare/mkarikom/Media/calibre-web:/config
      - /mnt/md0/insshare/mkarikom/Media/calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped

## Docker logs

[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
cp: cannot stat '/app/calibre-web/gdrive.db': No such file or directory
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
Creating symlinks...
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________

	Traceback (most recent call last):
	  File "calibre/linux.py", line 832, in setup_completion
	  File "calibre/linux.py", line 574, in write_completion
	  File "bypy-importer.py", line 203, in exec_module
	  File "calibre/gui2/__init__.py", line 16, in <module>
	ImportError: cannot import name 'QApplication' from 'PyQt5.Qt' (/app/calibre/lib/calibre-extensions/PyQt5.Qt.so)

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________

	Traceback (most recent call last):
	  File "calibre/linux.py", line 853, in setup_desktop_integration
	  File "calibre/linux.py", line 875, in do_setup_desktop_integration
	  File "calibre/linux.py", line 906, in install_xdg_junk
	  File "calibre/linux.py", line 891, in install_icons
	  File "calibre/linux.py", line 881, in install_single_icon
	  File "calibre/linux.py", line 1304, in render_img
	ImportError: cannot import name 'QImage' from 'PyQt5.Qt' (/app/calibre/lib/calibre-extensions/PyQt5.Qt.so)

Creating un-installer: /usr/bin/calibre-uninstall

There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/restricted Sources [7,198 B]
Get:5 http://archive.ubuntu.com/ubuntu focal/universe Sources [12.3 MB]
Get:6 http://archive.ubuntu.com/ubuntu focal/multiverse Sources [208 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal/main Sources [1,079 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1,275 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/main Sources [447 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/restricted Sources [11.3 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/universe Sources [183 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Sources [9,749 B]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [975 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [20.8 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [185 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [910 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-security/multiverse Sources [2,122 B]
Get:21 http://archive.ubuntu.com/ubuntu focal-security/restricted Sources [10.4 kB]
Get:22 http://archive.ubuntu.com/ubuntu focal-security/universe Sources [53.8 kB]
Get:23 http://archive.ubuntu.com/ubuntu focal-security/main Sources [148 kB]
Get:24 http://archive.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [13.3 kB]
Get:25 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [569 kB]
Get:26 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [652 kB]
Get:27 http://archive.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [154 kB]
Fetched 31.2 MB in 4s (8,180 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
3 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libllvm11 libpciaccess0 libsensors-config libsensors5
  libvulkan1 libwayland-client0 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0
  libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-sync1 libxcb-xfixes0
  libxdamage1 libxfixes3 libxshmfence1 libxxf86vm1 mesa-vulkan-drivers
Suggested packages:
  pciutils lm-sensors
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-intel1 libdrm-nouveau2 libdrm-radeon1
  libdrm2 libedit2 libelf1 libgl1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm11 libpciaccess0
  libsensors-config libsensors5 libvulkan1 libwayland-client0 libx11-xcb1
  libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-randr0
  libxcb-sync1 libxcb-xfixes0 libxdamage1 libxfixes3 libxshmfence1 libxxf86vm1
  mesa-vulkan-drivers
0 upgraded, 34 newly installed, 0 to remove and 3 not upgraded.
Need to get 32.4 MB of archives.
After this operation, 401 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libelf1 amd64 0.176-1.1build1 [44.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdrm-common all 2.4.102-1ubuntu1~20.04.1 [5,388 B]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdrm2 amd64 2.4.102-1ubuntu1~20.04.1 [32.3 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 libedit2 amd64 3.1-20191231-1 [87.0 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdrm-amdgpu1 amd64 2.4.102-1ubuntu1~20.04.1 [18.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/main amd64 libpciaccess0 amd64 0.16-0ubuntu1 [17.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdrm-intel1 amd64 2.4.102-1ubuntu1~20.04.1 [60.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdrm-nouveau2 amd64 2.4.102-1ubuntu1~20.04.1 [16.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libdrm-radeon1 amd64 2.4.102-1ubuntu1~20.04.1 [19.7 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libglapi-mesa amd64 20.2.6-0ubuntu0.20.04.1 [26.7 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libllvm11 amd64 1:11.0.0-2~ubuntu20.04.1 [17.6 MB]
Get:12 http://archive.ubuntu.com/ubuntu focal/main amd64 libsensors-config all 1:3.6.0-2ubuntu1 [6,092 B]
Get:13 http://archive.ubuntu.com/ubuntu focal/main amd64 libsensors5 amd64 1:3.6.0-2ubuntu1 [27.4 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal/main amd64 libvulkan1 amd64 1.2.131.2-1 [93.3 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgl1-mesa-dri amd64 20.2.6-0ubuntu0.20.04.1 [10.1 MB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libglvnd0 amd64 1.3.2-1~ubuntu0.20.04.1 [51.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libx11-xcb1 amd64 2:1.6.9-2ubuntu1.1 [9,220 B]
Get:18 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb-dri2-0 amd64 1.14-2 [6,920 B]
Get:19 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb-dri3-0 amd64 1.14-2 [6,552 B]
Get:20 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb-glx0 amd64 1.14-2 [22.1 kB]
Get:21 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb-present0 amd64 1.14-2 [5,560 B]
Get:22 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb-sync1 amd64 1.14-2 [8,884 B]
Get:23 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb-xfixes0 amd64 1.14-2 [9,296 B]
Get:24 http://archive.ubuntu.com/ubuntu focal/main amd64 libxdamage1 amd64 1:1.1.5-2 [6,996 B]
Get:25 http://archive.ubuntu.com/ubuntu focal/main amd64 libxfixes3 amd64 1:5.0.3-2 [10.9 kB]
Get:26 http://archive.ubuntu.com/ubuntu focal/main amd64 libxshmfence1 amd64 1.3-1 [5,028 B]
Get:27 http://archive.ubuntu.com/ubuntu focal/main amd64 libxxf86vm1 amd64 1:1.1.4-1build1 [10.2 kB]
Get:28 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libglx-mesa0 amd64 20.2.6-0ubuntu0.20.04.1 [142 kB]
Get:29 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libglx0 amd64 1.3.2-1~ubuntu0.20.04.1 [32.6 kB]
Get:30 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgl1 amd64 1.3.2-1~ubuntu0.20.04.1 [86.9 kB]
Get:31 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgl1-mesa-glx amd64 20.2.6-0ubuntu0.20.04.1 [5,540 B]
Get:32 http://archive.ubuntu.com/ubuntu focal/main amd64 libwayland-client0 amd64 1.18.0-1 [23.9 kB]
Get:33 http://archive.ubuntu.com/ubuntu focal/main amd64 libxcb-randr0 amd64 1.14-2 [16.3 kB]
Get:34 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 mesa-vulkan-drivers amd64 20.2.6-0ubuntu0.20.04.1 [3,700 kB]
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 34.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 34.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 32.4 MB in 3s (10.8 MB/s)
Selecting previously unselected package libelf1:amd64.
(Reading database ... 11935 files and directories currently installed.)
Preparing to unpack .../00-libelf1_0.176-1.1build1_amd64.deb ...
Unpacking libelf1:amd64 (0.176-1.1build1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../01-libdrm-common_2.4.102-1ubuntu1~20.04.1_all.deb ...
Unpacking libdrm-common (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../02-libdrm2_2.4.102-1ubuntu1~20.04.1_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../03-libedit2_3.1-20191231-1_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20191231-1) ...
Selecting previously unselected package libdrm-amdgpu1:amd64.
Preparing to unpack .../04-libdrm-amdgpu1_2.4.102-1ubuntu1~20.04.1_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libpciaccess0:amd64.
Preparing to unpack .../05-libpciaccess0_0.16-0ubuntu1_amd64.deb ...
Unpacking libpciaccess0:amd64 (0.16-0ubuntu1) ...
Selecting previously unselected package libdrm-intel1:amd64.
Preparing to unpack .../06-libdrm-intel1_2.4.102-1ubuntu1~20.04.1_amd64.deb ...
Unpacking libdrm-intel1:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libdrm-nouveau2:amd64.
Preparing to unpack .../07-libdrm-nouveau2_2.4.102-1ubuntu1~20.04.1_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libdrm-radeon1:amd64.
Preparing to unpack .../08-libdrm-radeon1_2.4.102-1ubuntu1~20.04.1_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Selecting previously unselected package libglapi-mesa:amd64.
Preparing to unpack .../09-libglapi-mesa_20.2.6-0ubuntu0.20.04.1_amd64.deb ...
Unpacking libglapi-mesa:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Selecting previously unselected package libllvm11:amd64.
Preparing to unpack .../10-libllvm11_1%3a11.0.0-2~ubuntu20.04.1_amd64.deb ...
Unpacking libllvm11:amd64 (1:11.0.0-2~ubuntu20.04.1) ...
Selecting previously unselected package libsensors-config.
Preparing to unpack .../11-libsensors-config_1%3a3.6.0-2ubuntu1_all.deb ...
Unpacking libsensors-config (1:3.6.0-2ubuntu1) ...
Selecting previously unselected package libsensors5:amd64.
Preparing to unpack .../12-libsensors5_1%3a3.6.0-2ubuntu1_amd64.deb ...
Unpacking libsensors5:amd64 (1:3.6.0-2ubuntu1) ...
Selecting previously unselected package libvulkan1:amd64.
Preparing to unpack .../13-libvulkan1_1.2.131.2-1_amd64.deb ...
Unpacking libvulkan1:amd64 (1.2.131.2-1) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../14-libgl1-mesa-dri_20.2.6-0ubuntu0.20.04.1_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Selecting previously unselected package libglvnd0:amd64.
Preparing to unpack .../15-libglvnd0_1.3.2-1~ubuntu0.20.04.1_amd64.deb ...
Unpacking libglvnd0:amd64 (1.3.2-1~ubuntu0.20.04.1) ...
Selecting previously unselected package libx11-xcb1:amd64.
Preparing to unpack .../16-libx11-xcb1_2%3a1.6.9-2ubuntu1.1_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.6.9-2ubuntu1.1) ...
Selecting previously unselected package libxcb-dri2-0:amd64.
Preparing to unpack .../17-libxcb-dri2-0_1.14-2_amd64.deb ...
Unpacking libxcb-dri2-0:amd64 (1.14-2) ...
Selecting previously unselected package libxcb-dri3-0:amd64.
Preparing to unpack .../18-libxcb-dri3-0_1.14-2_amd64.deb ...
Unpacking libxcb-dri3-0:amd64 (1.14-2) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../19-libxcb-glx0_1.14-2_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.14-2) ...
Selecting previously unselected package libxcb-present0:amd64.
Preparing to unpack .../20-libxcb-present0_1.14-2_amd64.deb ...
Unpacking libxcb-present0:amd64 (1.14-2) ...
Selecting previously unselected package libxcb-sync1:amd64.
Preparing to unpack .../21-libxcb-sync1_1.14-2_amd64.deb ...
Unpacking libxcb-sync1:amd64 (1.14-2) ...
Selecting previously unselected package libxcb-xfixes0:amd64.
Preparing to unpack .../22-libxcb-xfixes0_1.14-2_amd64.deb ...
Unpacking libxcb-xfixes0:amd64 (1.14-2) ...
Selecting previously unselected package libxdamage1:amd64.
Preparing to unpack .../23-libxdamage1_1%3a1.1.5-2_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.5-2) ...
Selecting previously unselected package libxfixes3:amd64.
Preparing to unpack .../24-libxfixes3_1%3a5.0.3-2_amd64.deb ...
Unpacking libxfixes3:amd64 (1:5.0.3-2) ...
Selecting previously unselected package libxshmfence1:amd64.
Preparing to unpack .../25-libxshmfence1_1.3-1_amd64.deb ...
Unpacking libxshmfence1:amd64 (1.3-1) ...
Selecting previously unselected package libxxf86vm1:amd64.
Preparing to unpack .../26-libxxf86vm1_1%3a1.1.4-1build1_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1build1) ...
Selecting previously unselected package libglx-mesa0:amd64.
Preparing to unpack .../27-libglx-mesa0_20.2.6-0ubuntu0.20.04.1_amd64.deb ...
Unpacking libglx-mesa0:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Selecting previously unselected package libglx0:amd64.
Preparing to unpack .../28-libglx0_1.3.2-1~ubuntu0.20.04.1_amd64.deb ...
Unpacking libglx0:amd64 (1.3.2-1~ubuntu0.20.04.1) ...
Selecting previously unselected package libgl1:amd64.
Preparing to unpack .../29-libgl1_1.3.2-1~ubuntu0.20.04.1_amd64.deb ...
Unpacking libgl1:amd64 (1.3.2-1~ubuntu0.20.04.1) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../30-libgl1-mesa-glx_20.2.6-0ubuntu0.20.04.1_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Selecting previously unselected package libwayland-client0:amd64.
Preparing to unpack .../31-libwayland-client0_1.18.0-1_amd64.deb ...
Unpacking libwayland-client0:amd64 (1.18.0-1) ...
Selecting previously unselected package libxcb-randr0:amd64.
Preparing to unpack .../32-libxcb-randr0_1.14-2_amd64.deb ...
Unpacking libxcb-randr0:amd64 (1.14-2) ...
Selecting previously unselected package mesa-vulkan-drivers:amd64.
Preparing to unpack .../33-mesa-vulkan-drivers_20.2.6-0ubuntu0.20.04.1_amd64.deb ...
Unpacking mesa-vulkan-drivers:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Setting up libxcb-dri3-0:amd64 (1.14-2) ...
Setting up libx11-xcb1:amd64 (2:1.6.9-2ubuntu1.1) ...
Setting up libpciaccess0:amd64 (0.16-0ubuntu1) ...
Setting up libxdamage1:amd64 (1:1.1.5-2) ...
Setting up libxcb-xfixes0:amd64 (1.14-2) ...
Setting up libglvnd0:amd64 (1.3.2-1~ubuntu0.20.04.1) ...
Setting up libxcb-glx0:amd64 (1.14-2) ...
Setting up libedit2:amd64 (3.1-20191231-1) ...
Setting up libsensors-config (1:3.6.0-2ubuntu1) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1build1) ...
Setting up libxcb-present0:amd64 (1.14-2) ...
Setting up libllvm11:amd64 (1:11.0.0-2~ubuntu20.04.1) ...
Setting up libxfixes3:amd64 (1:5.0.3-2) ...
Setting up libxcb-sync1:amd64 (1.14-2) ...
Setting up libsensors5:amd64 (1:3.6.0-2ubuntu1) ...
Setting up libglapi-mesa:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Setting up libvulkan1:amd64 (1.2.131.2-1) ...
Setting up libxcb-dri2-0:amd64 (1.14-2) ...
Setting up libxshmfence1:amd64 (1.3-1) ...
Setting up libxcb-randr0:amd64 (1.14-2) ...
Setting up libdrm-common (2.4.102-1ubuntu1~20.04.1) ...
Setting up libelf1:amd64 (0.176-1.1build1) ...
Setting up libwayland-client0:amd64 (1.18.0-1) ...
Setting up libdrm2:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Setting up mesa-vulkan-drivers:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Setting up libdrm-nouveau2:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Setting up libdrm-radeon1:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Setting up libdrm-intel1:amd64 (2.4.102-1ubuntu1~20.04.1) ...
Setting up libgl1-mesa-dri:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Setting up libglx-mesa0:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Setting up libglx0:amd64 (1.3.2-1~ubuntu0.20.04.1) ...
Setting up libgl1:amd64 (1.3.2-1~ubuntu0.20.04.1) ...
Setting up libgl1-mesa-glx:amd64 (20.2.6-0ubuntu0.20.04.1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/calibre-web:calibre files to container
[mod-init] linuxserver/calibre-web:calibre at sha256:449bfec252f6fa01942cb42abe5ea911cad987c5d9859b267a21f0647ba24f55 has been previously applied skipping
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by tobbenb** [comment]
You have to allow the user to read in the settings.
