### ISSUE TITLE
The 80 port is unable to use for WebUI

### ISSUE THREAD

**Issue by liuxingyulee** [linuxserver/docker-calibre-web#129]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Installed docker-calibre-web on the docker over NAS system, which was working good until change the WebUI port to 80.
Please indicate how to revert port back to 8083 in files, if it is possible, since the webUI is broken down.

In the Web configuration, there is an item to let admin user to change the port of WebUI. Because the IP of calibre-web is different with the IP of NAS physical port, so I try to change the port from 8083 to 8080, which was working. 
When I try to change port from 8080 to 80, the WebUI is unable to access and it shows permission denied on port 80 as below:
{"log":"Error starting server: [Errno 13] Permission denied: ('', 80)\r\n","stream":"stdout","time":"2021-02-10T23:55:30.90013279Z"}
------------------------------

## Expected Behavior
Either the calibre-web allows to use port 80 without permission issue or there should be a reminder for user avoiding setting port 80 for calibre-web on the Web settings.

## Current Behavior
It allow users to set port as 80 on the Web settings page, after that the port 80 is prevented from by the system, which make users unable to revert the configuration of port.

## Steps to Reproduce
1. set up calibre-web with Calibre;
2.change the port configuration from 8083 to 80;
3.apply the change;

## Environment
**OS:**Qnap Nas Q4.5.1
**CPU architecture:** x86_64
**How docker service was installed:** It is installed in Qnap Nas OS, pulled from official docker repo

## Command used to create docker container (run/create/compose/screenshot)
Change the port of WebUI from 8083 to 8080, it was working. Then change it to 80, it prompts 'Permission denied' error. 
Reinstall the image, it still report the default port is 80 and denied by system.

## Docker logs
{"log":"Error starting server: [Errno 13] Permission denied: ('', 80)\r\n","stream":"stdout","time":"2021-02-10T23:55:30.90013279Z"}

**Comment by CHBMB** [comment]
Don't change the port in the webui and just change how you've mapped it in your docker setup.

Alternatively if you do change it in the webui despite the above, you will need to change your docker setup accordingly.

**Comment by liuxingyulee** [comment]
Thanks for your explanation.
