### ISSUE TITLE
Can't upload ebook 

### ISSUE THREAD

**Issue by enefem** [linuxserver/docker-calibre-web#132]
## Expected Behavior

Ebook should be uploaded

## Current Behavior

Getting an error "could not saved to temp dir". Note that this is a new error as I can upload ebook several months ago.

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by j0nnymoe** [comment]
Please provide the info we asked for. We are unable to help otherwise.
