### ISSUE TITLE
DB location is not valid, please enter correct path

### ISSUE THREAD

**Issue by xhanrot** [linuxserver/docker-calibre-web#136]
I've just installed calibre-web on my Synology NAS. Here is of the relevant part of `docker inspect calibre-web` that outputs the configuration of my container :

```
"HostConfig": {
            "Binds": [
                "/volume2/Books:/books:rw",
                "/volume2/docker/calibre-web/config:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "8083/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8083"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PUID=1026",
                "PGID=100",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/root",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TERM=xterm",
                "TZ=Europe/Paris"
            ],
```
 And the output of `docker exec -it calibre-web ls -la /books/metadata.db` is :
```
 xavier@Synology:/$ sudo docker exec -it calibre-web ls -la /books/metadata.db
---------- 1 abc users 723968 Feb 13 12:08 /books/metadata.db
```
However, when I go to the web interface, it asks me the location of the calibre database. I fill it with `/books`, but I have an error message saying my DB location is not valid.

**Comment by tobbenb** [comment]
The container doesn't have any permissions on the file, so hard to read it for Calibre-web. This is a support issue and not an issue with the container, so please join our discord server or Discourse forum for support. Links in linuxsserver.io/support

You also ignored the issue template. Please supply the info we ask for in the template when asking for support on Discord or Discourse.

**Comment by cosmicbubble69** [comment]
i moved my metadata.db to the /config directory along with my ebooks and entered the /config path into the basicconfig UI and it worked.

**Comment by grigio** [comment]
I still had this issue

**Comment by xnuit** [comment]
> i moved my metadata.db to the /config directory along with my ebooks and entered the /config path into the basicconfig UI and it worked.

Maaan, I've trying for a whole day and this finally worked.
I had mapped two volumes in my container one for /config and another for /books I move my medatada to /config and changed the container volume mapping and it finally worked !
I still have no idea why it worked in the config file and not the /books volume ...
