### ISSUE TITLE
 linuxserver/calibre-web  文件无法推送的kindle

### ISSUE THREAD

**Issue by xixihha** [linuxserver/docker-calibre-web#139]
linuxserver/calibre-web是运行在qnap的nas Container 上面的，用amdin 账号运行。设置好了smtp，能正常发送测试邮件，但是发送书籍到kindle的时候kindle 一直无法收到书籍

**Comment by tobbenb** [comment]
Since you can't follow the issue template and post in English, I'm going to close the issue. When/if you post the info and in English we can reopen the issue.
