### ISSUE TITLE
Separate directory for database

### ISSUE THREAD

**Issue by GastonDiggler** [linuxserver/docker-calibre-web#145]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

It's should be interesting to have the possibility to have one directory for database and one for books and why not one for cover extract and nfo.

**Comment by drizuid** [comment]
I suspect you MAY be able to pass an environment variable `CALIBRE_DBPATH=/path/to/db` and of course map the volume. I havent tested this, but it's an environment variable supported by cps.py

**Comment by CHBMB** [comment]
The way calibre is setup is the database resides in the root folder of the books.  That's not something we can control with this container I'm afraid.  There are some [upstream plans in calibre-web to generate thumbnails](https://github.com/janeczku/calibre-web/pull/1771) etc, again when that's implemented upstream we'll account for that here.
