### ISSUE TITLE
Please help. How can I import all my books from a directory?

### ISSUE THREAD

**Issue by HuyangJake** [linuxserver/docker-calibre-web#148]
By the way, there is nothing happened, when I upload a single book using the upload function which trigger from the right-top button of the navigation bar.

Here are my system's information

|||
|-|-|
Platform | Linux 4.4.59+ #25556 SMP PREEMPT Thu Mar 18 13:00:34 CST 2021 x86_64 x86_64
Python | 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0]
Calibre_Web | 0.6.12 - 54d06e580d73ba58274e7ed4efbd8fc94b7e1856 - 2021-05-22T14:08:46+02:00
WebServer | Gevent 21.1.2

**Comment by drizuid** [comment]
Do you have a preexisting calibre database? This is required.

**Comment by CHBMB** [comment]
You don't import books from a directory, it uses a pre-existing calibre database
