### ISSUE TITLE
Calibredb location?

### ISSUE THREAD

**Issue by silentArtifact** [linuxserver/docker-calibre-web#15]
I'm working on linking LazyLibrarian to calibre-web, and apparently I need to find `calibredb` to make that happen. It looks as though it's not a part of this package... is it located somewhere I'm not seeing? Or is that primarily a part of the desktop client? Sorry, I know this is a weird question.

**Comment by thelamer** [comment]
You are correct this is not included in this application, it is only the web interface for interacting with the calibre database. 

To create a database you can do so from the CLI after installing calibredb: 
```
calibredb add /path/to/your/ebooks/* --library-path <The path you mounted to /books>
```

There is a good guide on DO here for general usage: 

https://www.digitalocean.com/community/tutorials/how-to-create-a-calibre-ebook-server-on-ubuntu-14-04

**Comment by sparklyballs** [comment]
as @thelamer has said you need to supply your own db for this

**Comment by artiomn** [comment]
Please, add calibredb inside a container. I need to build and rebuild calibre database on the server too.
And what do I need? Create my own container with a "calibre tools" or even run calibre-server container with a web interface?
