### ISSUE TITLE
Image config does not respect CALIBRE_DBPATH

### ISSUE THREAD

**Issue by samyak-jain** [linuxserver/docker-calibre-web#159]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

calibre-web has the ability to change the config path using CALIBRE_DBPATH. However, this image does not respect that. As we can see in this file: https://github.com/linuxserver/docker-calibre-web/blob/7c58d7f2c7ddc4f4f11efdaac98de84b16ba4fb4/root/etc/cont-init.d/30-config, the config path is hardcoded rather than picking it up from the environment variable provided by the user. 

## Current Behavior

It ignore CALIBRE_DBPATH leading to errors

## Steps to Reproduce

Add the CALIBRE_DBPATH environment variable when running the image. For example:
```sudo docker run -p 8083:8083 -it -e PUID=1000 -e GUID=1000 -e CALIBRE_DBPATH=/calibre/config linuxserver/calibre-web```

## Environment
**OS:** 5.13.13-arch1-1
**CPU architecture:** x86_64/arm32/arm64: x86
**How docker service was installed:** pacman

## Command used to create docker container (run/create/compose/screenshot)

```sudo docker run -p 8083:8083 -it -e PUID=1000 -e GUID=1000 -e CALIBRE_DBPATH=/calibre/config linuxserver/calibre-web```

## Docker logs

```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
cp: cannot stat '/app/calibre-web/gdrive.db': No such file or directory
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 253, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 368, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 611, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 605, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file
```

**Comment by j0nnymoe** [comment]
Forgive me if I've miss understood this, but even though you've added the `CALIBRE_DBPATH`, you haven't defined a volume related to this so it's not going to be able to find anything to open.

**Comment by Roxedus** [comment]
The linked code does not hardcode anything. 
The application looks to be always prioritizing that variable.
As Jonny mentioned, the folder you tell it to use does not exist in the container.

**Comment by samyak-jain** [comment]
@j0nnymoe @Roxedus It doesn't matter if I define a volume or not since the point of the 30-config file is to copy the the db files into the config directory. The application will search for the config in the CONFIG_DBPATH env variable if provided. Even if I provide a volume, it doesn't make the error go away: ```sudo docker run -p 8083:8083 -it -e PUID=1000 -e GUID=1000 -v /home/username/config:/calibre/config -e CALIBRE_DBPATH=/calibre/config linuxserver/calibre-web```. 

The file does hardcode the config directory since it assumes that it will always be ```/config```. However, as documented by the application https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface, the config directory can be changed by the user by adding the CALIBRE_DBPATH env variable.

**Comment by Roxedus** [comment]
We don't hardcode anything. We place a empty database in the assumed location of /config. 

My test yield the result you want, when provided with a database at the location of `CALIBRE_DBPATH`

This one starts up like expected.
```sh
wget -O app.db https://github.com/linuxserver/docker-calibre-web/blob/master/root/defaults/app.db\?raw\=true
docker run -it --rm --name=cw-test -e PUID=1000 -e PGID=1000 -p 8083:8083 -e CALIBRE_DBPATH=/calibre/config -v $PWD:/calibre/config linuxserver/calibre-web
```
This one doesn't, because there is no database in the supplied path
```sh
wget -O app.db https://github.com/linuxserver/docker-calibre-web/blob/master/root/defaults/app.db\?raw\=true
docker run -it --rm --name=cw-test -e PUID=1000 -e PGID=1000 -p 8083:8083 -e CALIBRE_DBPATH=/calibre/config -v $PWD:/calibre/other-config linuxserver/calibre-web
```

Do you expect us to move a default clean database to `CALIBRE_DBPATH`, even though assuming everybody that uses that variable probably already have a config?

**Comment by samyak-jain** [comment]
Ah. I see. I misunderstood what 30-config does. You're right then. Closing the issue.

**Comment by samyak-jain** [comment]
Quick question @Roxedus. There should be nothing *wrong* to have 30-config use CALIBRE_DBPATH, right? Since, if I'm understanding the code correctly, it does check for the existence of an existing DB so it will not overwrite existing data. Making this change helps when setting this for the first time.

**Comment by Roxedus** [comment]
No. But we don't really want to touch any directory outside of /config, unless we really need to.

This is a upstream variable, which we don't document in our readme, and therefore it's "unsupported" by us.
