### ISSUE TITLE
Calibre DB dependency clarification in the docker CLI example

### ISSUE THREAD

**Issue by Utopiah** [linuxserver/docker-calibre-web#161]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

According to numerous issues https://github.com/linuxserver/docker-calibre-web/issues/147 https://github.com/linuxserver/docker-calibre-web/issues/110 https://github.com/linuxserver/docker-calibre-web/issues/102 https://github.com/linuxserver/docker-calibre-web/issues/88 https://github.com/linuxserver/docker-calibre-web/issues/104 there are a lot of confusion on how this image can be used. I imagine it comes mostly from people use to copy/pasting the docker command line without reading the documentation. Adding a comment there could help these people see what the problem is without doing a file check in the logs.

------------------------------

## Desired Behavior
Work out of the box even without reading the documentation

## Current Behavior
Seems to work but only works for the Google Drive version.

## Alternatives Considered
```
  -v /path/to/data:/config \
  -v /path/to/data:/config `#Mandatory! You must have a Calibre setup first` \
  -v /path/to/calibre/library:/books \
  -v /path/to/calibre/library:/books `#Mandatory! You must have a Calibre correct database` \
```

**Comment by Utopiah** [comment]
Alternatively and for people wanting to use this container for the conversion capabilities having a default DB with e.g John Schember's Quick Start Guide, as Calibre does, could help a lot.

**Comment by j0nnymoe** [comment]
Yea this is a possibility. Though we already do state an existing database is required in the description: "Calibre-web is a web app providing a clean interface for browsing, reading and downloading eBooks using an existing Calibre database. " and also here:
![image](https://user-images.githubusercontent.com/10374553/133408141-bb5c3577-c1db-490e-b719-6193f70f2a0b.png)
We'll look at this soon I suspect.

**Comment by shubhank-saxena** [comment]
Hello @Utopiah . I used default DB. But now I just can't see the books that I upload to the relevant location to pop up in the library. Any clue on how I can fix this?

**Comment by Utopiah** [comment]
@shubhank-saxena I'm not actively using this image so I can't say. If you do have them in the correct location (according to your container, I suggest checking for within a shell in that context) with a working DB then you might want to open an issue.

**Comment by drizuid** [comment]
there is no "default db" and the readme already indicates you must have an existing calibre database, as does the application documentation.
