### ISSUE TITLE
CSP error

### ISSUE THREAD

**Issue by MartinHotmann** [linuxserver/docker-calibre-web#165]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Showing CSS, BLOB files and other images in book.

## Current Behavior
Not showing CSS, BLOBs and other images

## Steps to Reproduce

1. Open a .epub file
2. see no pictures
3. see console
4. see `Refused to load the image 'blob:https://domain.tld:8083/feba4cf7-ec9a-4b11-8861-908a5dbb175f' because it violates the following Content Security Policy directive: "img-src 'self' data:".`

## Environment
**OS:** Synology
**CPU architecture:** x86_64
**How docker service was installed:** docker-compoise.yml

## HowToResolve
add `blob:` to CSP `img-src`

**Comment by MartinHotmann** [comment]
Thanks, CSS and IMAGE is fixed now. (since last Update some hours ago)

But FONTS are still blocked:

![image](https://user-images.githubusercontent.com/17692860/139962054-0784f0a7-c2ae-4b39-9e08-5375da4cebc6.png)


Thanks in advance and thanks for the quick fix.

**Comment by MartinHotmann** [comment]
Push. Would really like to see fonts also to be loaded via BLOB, as the other issue (with IMAGES and STYLESHEETS) was fixed very fast.

Thanks

**Comment by MartinHotmann** [comment]
This just occurs for inline/embedded Fonts which are included in EPUB file.

**Comment by Roxedus** [comment]
Are you trying to propose changes for the upstream project?
