### ISSUE TITLE
When reading books online, images cannot be displayed or are displayed abnormally

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-calibre-web#168]
When reading books online, images cannot be displayed or are displayed abnormally

**Comment by evsasha** [comment]
@jxzzlfh i think it's was fixed in latest tags, try tag `2021.11.21`, i tried to read CBR and it was ok.

**Comment by drizuid** [comment]
> When reading books online, images cannot be displayed or are displayed abnormally

you need to fill out the template fully to get support.

**Comment by drizuid** [comment]
template not filled out
