### ISSUE TITLE
Epub viewer in v0.6.14 isn't displaying images

### ISSUE THREAD

**Issue by r00teniy** [linuxserver/docker-calibre-web#173]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Images in epub books should be displayed in "read in browser"
## Current Behavior

Epub viewer in v0.6.14 isn't displaying images
[Here](https://github.com/janeczku/calibre-web/issues/2162) you can see this issue in main Calibre Github, they released fix for it, so container needs to be updated to it probably.

## Steps to Reproduce

1. Open any epub book and you won't see any images

## Environment
**OS:** Raspbian 64bit
**CPU architecture:** arm64
**How docker service was installed:**  official repo

## Command used to create docker container (run/create/compose/screenshot) docker compose
![image](https://user-images.githubusercontent.com/3891119/148285628-87eba072-935b-45fc-8848-8cbe0feb613d.png)

## Docker logs

Nothing in logs

**Comment by Schocker360** [comment]
I am also experiencing this issue and can confirm that the fix is here: https://github.com/janeczku/calibre-web/commit/b414d9196417872d5bca443fee09d0a6e6c9efb0

**Comment by r00teniy** [comment]
After todays update images still don't show.

**Comment by Roxedus** [comment]
> After todays update images still don't show.

There is still no new release done. Switch to nightly if you need the commits after the latest release.

**Comment by r00teniy** [comment]
> > After todays update images still don't show.
> 
> There is still no new release done. Switch to nightly if you need the commits after the latest release.

ok will do it till 3.15 then, i just thought they fixed their 3.14 release, but it looks like i was wrong.

**Comment by drizuid** [comment]
closing as this is oudated and likely an upstream issue
