### ISSUE TITLE
Get rid of 2021 major tags

### ISSUE THREAD

**Issue by Ornias1993** [linuxserver/docker-calibre-web#174]
Currently the version scheme is semver: 6.14.0
However, there are old tags in calver as well: 2021.12.14

This leads to cases where people with automatic versioning setup for semver, get "updated" to an old calver tag.
Best solution for this is to wipe the old calver versions. Switching from semver to calver simply is not very compatible with any form of automatic versioning, such as renovate.

**Comment by drizuid** [comment]
We do not support or recommend auto updating. However, I will leave this open and we'll see if anyone is interesting in looking into this, even though the template was not properly filled out which would usually result in being closed.

**Comment by Ornias1993** [comment]
> We do not support or recommend auto updating. However, I will leave this open and we'll see if anyone is interesting in looking into this, even though the template was not properly filled out which would usually result in being closed.

To be clear:
I was not refering to individuals auto-updating. I was refering to downstream sources auto-updating.
Things like Helm Charts with automatic update CI, currently cannot reasonably consume this container.

It's bad enough that if this does not get fixed, i'll have to remove this App completely from our Helm Catalog.

**Comment by Roxedus** [comment]
While the "solution" is simple, getting rid of history is not something we do lightly, I would imagine you know that an action like this goes against anything touching on reproduceability.

As for the "impossible" claim, it seems to me that one could use package rules in renova to ignore tags starting with four digits.

**Comment by aptalca** [comment]
Please let's not get into `good vs bad docker practices`. Let's instead just skip to the end of that argument to save time and effort and settle on `agree to disagree`.

If I'm understanding correctly, you are maintaining a helm chart for this image (news to me) and you are using some sort of CI to update the versions in the helm chart. And it looks like you are using our `pseudo-semver` tags for that.

`Pseudo-semver` tags we push are a very recent and experimental endeavor. We have not advertised them anywhere. You can see them on docker hub and ghcr as tags, but we never publicized any info on them. It's not fair for anyone to have certain expectations on what they're for or how they're meant to be used.

At this point, I suggest you either don't rely on them, or update your CI to ignore the date based ones.

**Comment by Ornias1993** [comment]
> If I'm understanding correctly, you are maintaining a helm chart for this image (news to me)

I'm actually the maintainer of the biggest community repository of Apps/Helm-Charts for TrueNAS SCALE.

> you are using some sort of CI to update the versions in the helm chart

Renovate to be precise, one of the bigger players in that the industry of CI bumping of dependencies

> And it looks like you are using our pseudo-semver tags for that.

The problem is not semver vs calver, we can handle both. Nor is your pseudo semver (or pseudo-calver for that mater).
Technically (both in calver AND semver), 21.x.y, is a higher version than 1.x.y.

Due to that technicallity, moving from pseudo-calver (the old tags) to pseudo-semver (the new tags) cases issues, most likely not just with renovate.

> At this point, I suggest you either don't rely on them, or update your CI to ignore the date based ones.

It would also not mater if I was still using "version-vCALVER" or "version-vSEMVER' either, because the problem is in the numberings scheme.


 I'm not attacking you guys personally on that, you guys made an oversight with unexpected consequences and that's fine. All I'm asking is: make sure other people (and certainly not downstreams) are not needlessly effected by your descisions.

**Comment by Ornias1993** [comment]
> We are not the ones in control of the upstream app's versioning. 

Actually, there seems never to have been a calver release by the calibre-web team, unless i'm mistaking repositories:
https://github.com/janeczku/calibre-web/releases

> Some follow semver, most don't

I'm not complainging about semver vs calver (second time I explain), I just try to explain that having them all open as tags is causing issues and not done "cleanly". I just report a bug that more people might experience.

> We also make some modifications like if we detect a single period, we try to treat it like a major/minor and add the date as patch.

That's ofcoarse great thinking and also why I requested someone to look into that the current design is causing problems.

> What I'm trying to tell you is, it is not semver and should not be treated as such

So the tags you guys are using (and promoting) for years... are still not considered stable?
Like the "version-vx.y.z(.a)" format has been in use for at least 3 years by now.

> And certainly don't try and push your own expectations onto us.

Ahh yes, in an IT industry where versioning is incremental. *I* am the one with the wrong expectations.

> You made some assumptions that are not true and set your expectations incorrectly.

That's an odd statement, considering the basic principle of incremental versioning existed before either of us where born. It's not some "weird expectation" that projects using version numbers use incremental versions (regardless of  weither that's semver, calver or whateverver)

---

Anyway, i'm trying to in good faith report an issue with the versioning scheme and in return got scolded for having the "wrong" expectation of version numbers being incremental.

I get it: Tags are not guaranteed to be incremental, i'm not even saying I expect that.
What I tried to explain is that in the latest transition something has gone a bit 'wrong' for downstreams that depend on your containers. Yes, yes, I get it "unsupported etcetcetc", that does not mean you should go scolding people for even daring to request the problem to be mitigated.

---

To be frank, I was previously sceptical about how LSIO did their tagging and in the latest year had become more than happy with the minor changes being applied. This experience (reporting a minor issue and got scolded at like a 3 year old asking for candy), has lead me to conclude this project is still stable enough for any significant use.

I never even actually expected it to be fixed any time soon, just reported an issue as a courtesy.

A shame.

**Comment by Ornias1993** [comment]
> While the "solution" is simple, getting rid of history is not something we do lightly, I would imagine you know that an action like this goes against anything touching on reproduceability.
> 
> As for the "impossible" claim, it seems to me that one could use package rules in renovate to ignore tags starting with four digits.

I completely agree, I just reported the issue to ensure it's being taken into account (either now or in the future).
It never was the goal to get it fixed quickly or something.

We previously already had to make many packages rules for lsio and either might start nuking their containers or implement it again. But thanks for your advice :)

**Comment by Finkregh** [comment]
I'm aware this issue is years old, but the underlying issue persists and perhaps I missed it in the discussion or the docs:

how should the current version be read from the repo tags/releases?

The current latest is "(?:version-)0.6.23" and I do not see any sensible possibility besides limiting the version by the time since the tag has been created:

```json5
// renovate config

  "packageRules": [
    {
      matchPackageNames: ["linuxserver/calibre-web"],
      matchJsonata: ["newVersionAgeInDays < 30"],
      // allowedVersions: "<=1000.0.0", // not enough because old 5.33.2exists
    },
  ],
```

But somehow, renovate still proposes a version that is much older. @PrivatePuffin Did you find a solution for the TrueNAS stuff?
