### ISSUE TITLE
Unable to change default listening port

### ISSUE THREAD

**Issue by jeanfrancoisgratton** [linuxserver/docker-calibre-web#176]
I tried to automate building of the docker image by building my own container on top of the current container. This only because it is easier on my home tools to automate the launch without having to deal with extra params, etc (the same tools launches multiple containers).

The reason I went this path (Dockerfile on top of your image) is to disable lm.session_protection (the first sed command).

This is my (simplified) Dockerfile, with some explanations below:
```
FROM lscr.io/linuxserver/calibre-web

ENV TZ="America/Montreal"
ENV PUID=9000
ENV GUID=1300
ENV DOCKER_MODS=linuxserver/calibre-web:calibre
ENV OAUTHLIB_RELAX_TOKEN_SCOPE=1
ENV CALIBRE_PORT=2699
ENV DEFAULT_PORT=2699

RUN sed -i -e "s/^lm.session_protection = 'strong'/#.session_protection = 'strong'/" /app/calibre-web/cps/init.py
RUN sed -i -e "s/^DEFAULT_PORT = 8083/DEFAULT_PORT = ${DEFAULT_PORT}/" /app/calibre-web/cps/constants.py

VOLUME [ "/config", "/books" ]
EXPOSE ${DEFAULT_PORT}
```
Two things:

I am not sure that both CALIBRE_PORT and DEFAULT_PORT are needed. Does one supercede the other ?
The 2 RUN commands, the sed were added in a subsequent attempt as I could not see the changes being applied after a docker build.
Whatever I do these steps above, once in the container I still see this:

```
root@bookreader:/app# root@bookreader:/# netstat -pean|egrep "2699|8083" ;echo;echo;egrep -r "DEFAULT_PORT|CALIBRE_PORT|8083" /app
tcp6       0      0 :::8083                 :::*                    LISTEN      9000       30493054   -                   


/app/calibre-web/README.md:Point your browser to `http://localhost:8083` or `http://localhost:8083/opds` for the OPDS catalog
/app/calibre-web/cps/config_sql.py:    config_port = Column(Integer, default=constants.DEFAULT_PORT)
/app/calibre-web/cps/config_sql.py:    config_external_port = Column(Integer, default=constants.DEFAULT_PORT)
/app/calibre-web/cps/constants.py:DEFAULT_PORT        = 2699
/app/calibre-web/cps/constants.py:env_CALIBRE_PORT = os.environ.get("CALIBRE_PORT", DEFAULT_PORT)
/app/calibre-web/cps/constants.py:    DEFAULT_PORT = int(env_CALIBRE_PORT)
/app/calibre-web/cps/constants.py:    print('Environment variable CALIBRE_PORT has invalid value (%s), faling back to default (8083)' % env_CALIBRE_PORT)
/app/calibre-web/cps/constants.py:del env_CALIBRE_PORT
/app/calibre-web/cps/reverseproxy.py:        proxy_pass http://127.0.0.1:8083;
```

This is on version 0.6.16 ; for some reason I just cannot change the default port.
Any idea on what I might be missing ?

Thx

**Comment by tobbenb** [comment]
This is not something we support as you are building your own container on top of ours. You have also added extra stuff instead of following the readme.
