### ISSUE TITLE
without internet image can not run first time.

### ISSUE THREAD

**Issue by hppyworld** [linuxserver/docker-calibre-web#177]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. pull the image.
2. disconnect from internet
3. run the image without internet
4. wait for few seconds and then it shows below error timeout. and it could not load also in browser

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

## Docker logs

calibre-web    | [cont-init.d] 10-adduser: exited 0.
calibre-web    | [cont-init.d] 30-config: executing... 
calibre-web    | [cont-init.d] 30-config: exited 0.
calibre-web    | [cont-init.d] 90-custom-folders: executing... 
calibre-web    | [cont-init.d] 90-custom-folders: exited 0.
calibre-web    | [cont-init.d] 99-custom-scripts: executing... 
calibre-web    | [custom-init] no custom files found exiting...
calibre-web    | [cont-init.d] 99-custom-scripts: exited 0.
calibre-web    | [cont-init.d] done.
calibre-web    | [services.d] starting services
calibre-web    | [services.d] done.
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
calibre-web    |     h.request(req.get_method(), req.selector, req.data, headers,
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1256, in request
calibre-web    |     self._send_request(method, url, body, headers, encode_chunked)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
calibre-web    |     self.endheaders(body, encode_chunked=encode_chunked)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
calibre-web    |     self._send_output(message_body, encode_chunked=encode_chunked)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
calibre-web    |     self.send(msg)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 951, in send
calibre-web    |     self.connect()
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1418, in connect
calibre-web    |     super().connect()
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 922, in connect
calibre-web    |     self.sock = self._create_connection(
calibre-web    |   File "/usr/lib/python3.8/socket.py", line 808, in create_connection
calibre-web    |     raise err
calibre-web    |   File "/usr/lib/python3.8/socket.py", line 796, in create_connection
calibre-web    |     sock.connect(sa)
calibre-web    | socket.timeout: timed out
calibre-web    | 
calibre-web    | During handling of the above exception, another exception occurred:
calibre-web    | 
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
calibre-web    |     with contextlib.closing(urlopen(
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
calibre-web    |     return opener.open(url, data, timeout)
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 525, in open
calibre-web    |     response = self._open(req, data)
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
calibre-web    |     result = self._call_chain(self.handle_open, protocol, protocol +
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
calibre-web    |     result = func(*args)
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
calibre-web    |     return self.do_open(http.client.HTTPSConnection, req,
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
calibre-web    |     raise URLError(err)
calibre-web    | urllib.error.URLError: <urlopen error timed out>
calibre-web    | 
calibre-web    | During handling of the above exception, another exception occurred:
calibre-web    | 
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 154, in load
calibre-web    |     for item in get_browsers(verify_ssl=verify_ssl):
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 97, in get_browsers
calibre-web    |     html = get(settings.BROWSERS_STATS_PAGE, verify_ssl=verify_ssl)
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
calibre-web    |     raise FakeUserAgentError('Maximum amount of retries reached')
calibre-web    | fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
calibre-web    | 
calibre-web    | During handling of the above exception, another exception occurred:
calibre-web    | 
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
calibre-web    |     h.request(req.get_method(), req.selector, req.data, headers,
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1256, in request
calibre-web    |     self._send_request(method, url, body, headers, encode_chunked)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
calibre-web    |     self.endheaders(body, encode_chunked=encode_chunked)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
calibre-web    |     self._send_output(message_body, encode_chunked=encode_chunked)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
calibre-web    |     self.send(msg)
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 951, in send
calibre-web    |     self.connect()
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 1418, in connect
calibre-web    |     super().connect()
calibre-web    |   File "/usr/lib/python3.8/http/client.py", line 922, in connect
calibre-web    |     self.sock = self._create_connection(
calibre-web    |   File "/usr/lib/python3.8/socket.py", line 808, in create_connection
calibre-web    |     raise err
calibre-web    |   File "/usr/lib/python3.8/socket.py", line 796, in create_connection
calibre-web    |     sock.connect(sa)
calibre-web    | socket.timeout: timed out
calibre-web    | 
calibre-web    | During handling of the above exception, another exception occurred:
calibre-web    | 
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 64, in get
calibre-web    |     with contextlib.closing(urlopen(
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
calibre-web    |     return opener.open(url, data, timeout)
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 525, in open
calibre-web    |     response = self._open(req, data)
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
calibre-web    |     result = self._call_chain(self.handle_open, protocol, protocol +
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
calibre-web    |     result = func(*args)
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
calibre-web    |     return self.do_open(http.client.HTTPSConnection, req,
calibre-web    |   File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
calibre-web    |     raise URLError(err)
calibre-web    | urllib.error.URLError: <urlopen error timed out>
calibre-web    | 
calibre-web    | During handling of the above exception, another exception occurred:
calibre-web    | 
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/app/calibre-web/cps.py", line 34, in <module>
calibre-web    |     from cps.about import about
calibre-web    |   File "/app/calibre-web/cps/about.py", line 61, in <module>
calibre-web    |     from scholarly import scholarly
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/scholarly/__init__.py", line 4, in <module>
calibre-web    |     scholarly = _Scholarly()
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/scholarly/_scholarly.py", line 27, in __init__
calibre-web    |     self.__nav = Navigator()
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 45, in __call__
calibre-web    |     cls._instances[cls] = super(Singleton, cls).__call__(*args,
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/scholarly/_navigator.py", line 59, in __init__
calibre-web    |     self.pm = ProxyGenerator()
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 54, in __init__
calibre-web    |     self._new_session()
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/scholarly/_proxy_generator.py", line 368, in _new_session
calibre-web    |     'User-Agent': UserAgent().random,
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 69, in __init__
calibre-web    |     self.load()
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/fake.py", line 75, in load
calibre-web    |     self.data = load_cached(
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 250, in load_cached
calibre-web    |     update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 245, in update
calibre-web    |     write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 187, in load
calibre-web    |     ret = json.loads(get(
calibre-web    |   File "/usr/local/lib/python3.8/dist-packages/fake_useragent/utils.py", line 84, in get
calibre-web    |     raise FakeUserAgentError('Maximum amount of retries reached')
calibre-web    | fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

**Comment by j0nnymoe** [comment]
Not much we can do if the application itself wants access to the internet.
