### ISSUE TITLE
new advanced searches showing old results and excluding series doesn't work

### ISSUE THREAD

**Issue by Andei** [linuxserver/docker-calibre-web#178]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
New advanced search with new results / excluding series

## Current Behavior
Second advanced search shows the old result with the old parameters.
Some flags create new results and some don't.
Excluding series never works

## Steps to Reproduce

1. search for epubs with eg. to-read flag=true
2. second search for epubs with to-read flag=true and another flag
3. same result as in step 1
4. excluding all series never works

## Environment
**OS:** Docker 20.10.3-1239, docker-compose, calibre-web 0.6.16
**CPU architecture:** Synology 918+, DSM 7.0.1-42218
**How docker service was installed:** Docker 20.10.3-1239, docker-compose, calibre-web 0.6.16
## Command used to create docker container (run/create/compose/screenshot)

`version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/apps/calibre-web:/config
      - /volume1/homes/andre/Drive/Calibre_Drive:/books
    ports:
      - 8083:8083
    restart: unless-stopped`
## Docker logs

nothing in log

**Comment by j0nnymoe** [comment]
Better to be reported upstream.
