### ISSUE TITLE
Login loop after update

### ISSUE THREAD

**Issue by CWempe** [linuxserver/docker-calibre-web#179]
After updating my docker container from an old `technosoft2000/calibre-web` to a new `linuxserver/calibre-web` I cannot use `calibre-web` via **Nginx Proxy Manager**.

I noticed the `gid` from the `docker logs` output does not match the defined `PGID`. 🤷‍♀️

## Expected Behavior
Get redirected to the library after login.

## Current Behavior
I get the login screen after I successfully log in. *infinite loop*

I works wehen I use the local address instead of the public address via reverse proxy.

## Steps to Reproduce
1. Run container
2. Configure Nginx Proxy Manager
3. Open calibre-web in browser
4. Login in
5. get redirected to Ligion page 

## Environment
 - OS: Debian
 - CPU architecture: x86_64
 - Calibre-Web version: latest, I guess
 - Docker container: `linuxserver/calibre-web` (tried `latest` and `nightly`)
 - Special Hardware: none
 - Browser: Chrome 98.0.4758.102
 - Nginx Proxy Manager: v2.9.16

**How docker service was installed:**
https://docs.docker.com/engine/install/debian/#install-using-the-repository

## Command used to create docker container (run/create/compose/screenshot)

```shell
IMAGE_NAME="lscr.io/linuxserver/calibre-web"
IMAGE_TAG="latest"
CONTAINER_NAME="calibre-web"
CONTAINER_VOLUME_CONFIG=${CONTAINER_NAME}-config
RESTARTPOLICY="unless-stopped"

docker run \
  --name=${CONTAINER_NAME} \
  --hostname=${CONTAINER_NAME} \
  --net=pub_net \
  --ip=192.168.1.139\
  --volume ${CONTAINER_VOLUME_BOOKS}:/books \
  --volume ${CONTAINER_VOLUME_CONFIG}:/config \
  --env USE_CONFIG_DIR=true \
  --env PGID=1011 \
  --env PUID=100 \
  --env TZ=Europe/Berlin \
  --detach \
  --restart=${RESTARTPOLICY} \
  ${IMAGE_NAME}:${IMAGE_TAG}

```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    100
User gid:    65534
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

**calibre-web.log**
```
[2022-02-27 15:22:55,741]  INFO {cps:141} Starting Calibre Web...
[2022-02-27 15:22:55,828]  INFO {cps.server:204} Starting Gevent server on [::]:8083
```

##Additional context

![image](https://user-images.githubusercontent.com/1270359/155860501-af1e377c-4ce1-4297-b1ef-624215682bbc.png)

Here is my Nginx Proxy Manager config:

![image](https://user-images.githubusercontent.com/1270359/155860593-b6f5acc0-c53f-4d55-b154-450a7d054b76.png)

![image](https://user-images.githubusercontent.com/1270359/155860602-7e38c9f6-4362-479d-ac81-490111c742f5.png)

![image](https://user-images.githubusercontent.com/1270359/155860612-5514ac93-5eb7-478b-a51e-2c5ef5455165.png)

**Comment by aptalca** [comment]
Try accessing directly via ip and if it works, it's an npm issue and should be reported to them.

If it doesn't work via direct access by ip, then we can help troubleshoot.

**Comment by CWempe** [comment]
Yes, it works with `http://192.168.1.139:8083/`.

I agree it does not look like a `linuxserver/docker-calibre-web` issue.
But since there is a [documentation about how to use Nginx](https://github.com/linuxserver/docker-calibre-web#:~:text=for%20other%20instances%20of%20Nginx) with this container I was hoping someone could confirm my configuration is correct.
Or maybe anybody else had the same issue.

**Comment by aptalca** [comment]
We support our own nginx based reverse proxy solution, which is called SWAG; and here's the preset conf for it: https://github.com/linuxserver/reverse-proxy-confs/blob/master/calibre-web.subdomain.conf.sample

**Comment by CWempe** [comment]
I got it working.

As mentioned [here](https://www.reddit.com/r/nginxproxymanager/comments/pme3os/comment/hckpknt/?utm_source=share&utm_medium=web2x&context=3) deleting and recreating the proxy configuration solved the issue.

Still strange...

**Comment by CWempe** [comment]
I got the same issue again.

This time, I cannot solve it by recreating the Nginx PM config. 😞
