### ISSUE TITLE
How To Setup On QNAP Container Station

### ISSUE THREAD

**Issue by ltjdym** [linuxserver/docker-calibre-web#18]
Sorry, noob here.

How do I use this in QNAP COntainer Station? I called support but they couldn't help.
When creating the container, what do I enter for "Command" and "Entrypoint" ?

Do I need to enter into advanced settings? Thanks in advance!

**Comment by j0nnymoe** [comment]
We have a generic guide for setting up containers on QNAP here: https://blog.linuxserver.io/2017/09/17/how-to-setup-containers-on-qnap/ , this should be enough to get any container running.
