### ISSUE TITLE
cannot remove the books through the ‘remove selections’ button in the books list 

### ISSUE THREAD

**Issue by BenBenJian** [linuxserver/docker-calibre-web#180]
Go to 'books list'
Click on 'any of the books'
Click on remove selections
cannot remove any of the books.
[Calibre-Web-debug-pack.zip](https://github.com/janeczku/calibre-web/files/8202326/Calibre-Web-debug-pack.zip)
[Uploading Calibre-Web-debug-pack.zip…]()

**Comment by drizuid** [comment]
template not filled out
