### ISSUE TITLE
Clicking on author in book list causes "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

### ISSUE THREAD

**Issue by ElFerminador** [linuxserver/docker-calibre-web#181]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When clicking on an author link of a book, it should show a list of all the author's books

## Current Behavior
I get an error 500. It's not consistent, though - sometimes it works, sometimes it doesn't.

## Steps to Reproduce
1. Log into the server.
2. Click on the author link on any book displayed on the first page (doesn't matter, actually, could also be from a search result or series list)
3. See error "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
4. The error is non-recoverable. I have to restart the docker container to get calibre-web up and running again

## Environment
**OS:** Synology DSM 7.0.1-422218 Update 2 
**CPU architecture:** x86_64 (Intel Xeon D-1527, Synology DS3617xsII NAS)
**How docker service was installed:** Synology Docker application

## Command used to create docker container (run/create/compose/screenshot) 
version: "3"
services:
  calibre-web:
    container_name: calibre-web
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - PGID=100
      - PUID=1027
    hostname: linuxserver-calibre-web1
    image: linuxserver/calibre-web:latest
    ipc: private
    labels:
      build_version: 'Linuxserver.io version:- 0.6.14-ls136 Build-date:- 2021-10-31T12:07:33+01:00'
      maintainer: chbmb
      org.opencontainers.image.authors: linuxserver.io
      org.opencontainers.image.created: 2021-10-31T12:07:33+01:00
      org.opencontainers.image.description: "[Calibre-web](https://github.com/janeczku/calibre-web)\
        \ is a web app providing a clean interface for browsing, reading and downloading\
        \ eBooks using an existing Calibre database.   It is also possible to integrate\
        \ google drive and edit metadata and your calibre library through the app\
        \ itself.    This software is a fork of library and licensed under the GPL\
        \ v3 License.  "
      org.opencontainers.image.documentation: https://docs.linuxserver.io/images/docker-calibre-web
      org.opencontainers.image.licenses: GPL-3.0-only
      org.opencontainers.image.ref.name: 030a05db7d8f9f3ffef8026e8f4b2e397a55de2e
      org.opencontainers.image.revision: 030a05db7d8f9f3ffef8026e8f4b2e397a55de2e
      org.opencontainers.image.source: https://github.com/linuxserver/docker-calibre-web
      org.opencontainers.image.title: Calibre-web
      org.opencontainers.image.url: https://github.com/linuxserver/docker-calibre-web/packages
      org.opencontainers.image.vendor: linuxserver.io
      org.opencontainers.image.version: 0.6.14-ls136
    logging:
      driver: db
      options: {}
    mac_address: 02:42:ac:11:00:03
    ports:
      - 8081:8083/tcp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /volume1/docker/calibre-web/config:/config
      - /volume1/docker/calibre-web/books:/calibre:ro
networks: {}
## Docker logs

[calibre-web.log](https://github.com/linuxserver/docker-calibre-web/files/8239817/calibre-web.log)

**Comment by ElFerminador** [comment]
Just something additional I forgot to mention - my library is mounted in **read-only** mode. I don't like having multiple systems doing edits on my Calibre library, that's why I mount it that way. Maybe too paranoid?

**Comment by ElFerminador** [comment]
... and something more: I just tested with the library being mounted in normal mode, where Calibre Web could write to it. No issues at all, I can click on links all I like and no crashes. 

I've been using Calibre Web for quite some time now, and the Calibre database was always mounted in read-only mode, with no issues at all. Any chance that this can be fixed? I'd really be able to mount my ebook library in read-only mode. Unless of course I'm worrying about nothing and Calibre isn't as fragile as I think it is. The way I sync is having my Calibre library in a dropbox folder, edits are done on my Mac. The dropbox folder gets synchronized to my Synology NAS to /volume1/docker/calibre-web/books, which I mount into the container at /calibre.

**Comment by tobbenb** [comment]
You have to ask calibre-web if it's possible to get it to work using a read only database. 
That's not something we can fix, as we are just packing the app.

Closing this as it's not a container issue.
