### ISSUE TITLE
no the button to "send to kindle"

### ISSUE THREAD

**Issue by notjiangjiu** [linuxserver/docker-calibre-web#190]
What do I need to set to appear?
the "E-mail Server Settings" is complete
i used docker install calibre-web，vision 0.6.18

**Comment by notjiangjiu** [comment]
![屏幕截图 2022-04-20 163431](https://user-images.githubusercontent.com/46511514/164187650-9c5a8809-df4d-4feb-9ab8-25fdcc3a8b0d.png)

**Comment by billouetaudrey** [comment]
Hi,

How to enable it for send directly epub to kindle ?

Thanks

**Comment by aptalca** [comment]
https://github.com/janeczku/calibre-web/issues/2067
