### ISSUE TITLE
Support cache directory

### ISSUE THREAD

**Issue by mmonkey** [linuxserver/docker-calibre-web#191]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Now that the [generate cover thumbnail cache PR](https://github.com/janeczku/calibre-web/pull/1771) has now been merged, there is a new ENV variable that dictates the new `cache` directory.

This directory defaults to the path: `<calibre-web root>/cps/cache`, but can be overridden by declaring a path with the `CACHE_DIR` environment variable; [see here](https://github.com/janeczku/calibre-web/pull/1771/files#diff-d07b9f505956d7b0c95d199ccf3d79e5e85895e4f21b725e1ebff28a4bb8649cR43).

This maybe as simple as updating the documentation and testing, but I haven't looked too deeply into it due to limited time.

**Comment by OzzieIsaacs** [comment]
One remark: the PR is currently merged to the development branch, it will take some days to be visible in the master branch

**Comment by OzzieIsaacs** [comment]
The PR is now merged to the master branch, the new environmental variable can be used
