### ISSUE TITLE
fetch metadata doesn't work

### ISSUE THREAD

**Issue by free521521521** [linuxserver/docker-calibre-web#193]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

fetch metadata doesn't work
------------------------------

## Expected Behavior

fetch metadata from the source
## Current Behavior

the page turn into frozen, and after a while the docker reboot again, then I can use the calibre-web again
## Steps to Reproduce

1. Press fetch metadata, 
2. Press the search,
3. Page fronze
4. Rebppt

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by drizuid** [comment]
I used your instructions for reproduction and had no issues. Unfortunately, you did not fill out the issue template so this is very much lacking in detail. I'll close this next week barring the missing details being provided.
