### ISSUE TITLE
/config volume is ignored

### ISSUE THREAD

**Issue by matejdro** [linuxserver/docker-calibre-web#194]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Calibre-web should be using /config folder for `app.db`, as mentioned in documentation:

`/config - Where calibre-web stores the internal database and config.`

## Current Behavior

Calibre-web stores its db in `/books` folder

## Steps to Reproduce
1. Start docker image with `-v /path-to-my-config-folder:/config` flag
2. Wait for calibre web to start
3.Open target folder - it is empty
4.Open books folder - database is there

## Environment
**OS:** `Linux server 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
**How docker service was installed:** from the official ubuntu repo

## Command used to create docker container (run/create/compose/screenshot)

```
docker run -d --name calibre-web \
    -v /path/to/config:/config \
    -v /path/to/books:/books \
    -e TZ=Europe/Ljubljana \
    -p 8038:8083 \
    -e PUID=111 \
    -e PGID=111 \
    --restart=always \
    technosoft2000/calibre-web:latest
```

**Comment by facorazza** [comment]
What are the permissions for the config directory? Does it already exist on the host machine or is it created by docker?

Perhaps you just need to `chown -R 111:111 config`

**Comment by j0nnymoe** [comment]
OP isn't using our container. Closing.
