### ISSUE TITLE
`ebook-convert` for arm

### ISSUE THREAD

**Issue by wietsedv** [linuxserver/docker-calibre-web#198]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The `calibre` Docker Mod (in the `calibre` branch of this repo) adds the `ebook-convert` binary. But only for x86-64. Calibre 6 adds official arm-support. Can arm-support be added to this image?

------------------------------

## Desired Behavior

ARM-images for the Calibre Docker Mod.

## Current Behavior

It's x86-only right now, because upstream arm-support was previously missing.

## Alternatives Considered

None

**Comment by gabbe222** [comment]
So this is why i get this error?
`[2022-07-16 23:43:33,324]  INFO {cps.editbooks:1146} converting: book id: 917 from: EPUB to: MOBI
[2022-07-16 23:43:33,335]  INFO {cps.tasks.convert:142} Book id 917 - target format of .mobi does not exist. Moving forward with convert.
[2022-07-16 23:43:33,366]  INFO {cps.tasks.convert:189} ebook converter failed with error while converting book`

**Comment by thespad** [comment]
This has been added with https://github.com/linuxserver/docker-mods/pull/402

Note that it *only* supports arm64. There is no support for arm32.
