### ISSUE TITLE
ERROR 500 version 64 crashes on startup 

### ISSUE THREAD

**Issue by slcb** [linuxserver/docker-calibre-web#20]
I deployed the container, configured with a PUID/PGID (generic docker user with all required permissions), set /config and /books to 2 empty folders. Connect to xxxx:8083 and can see the web admin interface. After setting options, I get "Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.".

Running Debian 9.4 Openmediavault 4, latest docker.

Logs attached.

Thank you for looking into this

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 Debian 9.4 running Openmediavault 4

[calibre_settings.txt](https://github.com/linuxserver/docker-calibre-web/files/2114370/calibre_settings.txt)

![capture](https://user-images.githubusercontent.com/22263338/41584866-52e52cc0-73a0-11e8-9a92-1e282adb7c77.PNG)

 attached calibre.log
[calibre.log](https://github.com/linuxserver/docker-calibre-web/files/2114356/calibre.log)

No symlinks, all directories are in /srv/drv-by-id.../
my whole /var/lib/docker directory is a symlink to another partition, a bunch of 6 other dockers is running fine with that and it is the "official" method found in docker man

**Comment by Trisk3lion** [comment]
I'm getting the same error.  Would really appreciate some insight!

**Comment by thefunkygibbon** [comment]
ditto :(

**Comment by j0nnymoe** [comment]
As you are getting the webui up and this is crashing when you have changed settings, please report this issue directly to the calibre-web github and they should be able to point out why it's not working. If it is indeed an issue with our container, please re-open the issue.

**Comment by Trisk3lion** [comment]
I tried another calibre-web container and got it working at last. 
My advice is to double check that all you files and folders in /config and, especially, /books have the same owner and group as you container. 
That fixed it for me in the end.

**Comment by CHBMB** [comment]
I've been running this since we released it and can't reproduce any crashes.

Also if you're pointing `/books` at an empty folder it probably will crash, from the readme....

`-v /books - where your calibre database is located`
