### ISSUE TITLE
Conversion to PDF not working

### ISSUE THREAD

**Issue by acamposcar** [linuxserver/docker-calibre-web#204]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce
Try to convert from EPUB or MOBI to PDF. (I didn't try other input formats)

## Environment
**OS:** Docker running on Windows 10 and Docker running on Synology
**CPU architecture:** x64
**How docker service was installed:**
From official repo

## Docker logs
1% Converting input to HTML...
Failed to import PyQt module: PyQt6.QtWebEngineCore with error: libXtst.so.6: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/ebooks/conversion/cli.py", line 419, in main
  File "calibre/ebooks/conversion/plumber.py", line 1106, in run
  File "calibre/ebooks/conversion/plugins/pdf_output.py", line 149, in specialize_options
ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)

**Comment by nrylov** [comment]
Try installing the libxtst6 package on your container. I had a similar issue where I was missing the libx11-dev package, but not libxtst.

**Comment by li-yu** [comment]
@nrylov Can you tell me how to install libxtst6 package in detail? I am a newbie, thank you.

**Comment by LukeG20** [comment]
@li-yu @nrylov Could either of you clarify how you install libxtst6? I'm guessing the same error after updating.

**Comment by drizuid** [comment]
you can **probably** use https://github.com/linuxserver/docker-mods/tree/universal-package-install to install libxts6 in calibre-web.

**Comment by drizuid** [comment]
hello, would you be willing to test 
lspipepr/calibre-web:amd64-0.6.19-pkg-3f37fbba-pr-230
and let us know if it resolves the issues?
