### ISSUE TITLE
Calibre-web on synology DS220+

### ISSUE THREAD

**Issue by fishwithwings** [linuxserver/docker-calibre-web#207]
Hi all,
I am trying to setup my Synology with Calibre web.  After running the task on the task scheduler, I get the following error report from my Synology:

Any help would be appreciated.  Thanks!

Task Scheduler has completed a scheduled task.

Task: Install Calibre-web
Start time: Sun, 28 Aug 2022 15:06:12 GMT
Stop time: Sun, 28 Aug 2022 15:06:12 GMT
Current status: 126 (Interrupted)
Standard output/error:
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=calibre-web": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by drizuid** [comment]
You need to fill out the issue template fully. We do not recommend using the synology ui to deploy containers (unless you plan to support it yourself) as it causes issues, our suggestion is for you to use docker compose or docker cli. All I can tell from what you provided above is that you have a permissions issue.

**Comment by drizuid** [comment]
no updates from OP
