### ISSUE TITLE
Image uses vulnerable version of OpenSSL

### ISSUE THREAD

**Issue by Algebro7** [linuxserver/docker-calibre-web#217]
There is a [critical OpenSSL vulnerability](https://malwaretechcom/2022/11/everything-you-need-to-know-about-the-openssl-3-0-7-patch.html) dropping soon that affects OpenSSL v3.0.0-3.0.6. I checked today and it looks like the latest version of the docker-calibre-web image is using OpenSSL 3.0.2:

```
# docker exec -it calibre-web /bin/bash
root@c8a9381d9722:/# openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

The fix is in 3.0.7 which I believe should be rolling out today. Just wanted to put this on the maintainers' radar.

Thanks!

**Comment by Roxedus** [comment]
We are aware, see https://github.com/linuxserver/docker-plex/issues/344
