### ISSUE TITLE
doesn't work after last pull

### ISSUE THREAD

**Issue by airdogvan** [linuxserver/docker-calibre-web#218]
Been running for the last year and a half with monthly pulls, never any problems.

Expected behaviour: docker starts the container.

Current behaviour: please see logs below.

Steps to reproduce: try running the docker-compose file below.

Environment: Ubuntu 20.04 LTS. CPU: x86_64.  Docker install with apt install

Command used to start the container: docker-compose up

Docker logs: please see blow.

Please find below my docker-compose for reference:

version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    volumes:
      - ./config:/config
      - /home/cheeseplant/calibre/books:/books
    restart: unless-stopped

Yesterday did a pull and this is the log when I did docker-compose up:

[custom-init] No custom files found, skipping...
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/app/calibre-web/cps.py", line 31, in <module>
calibre-web    |     main()
calibre-web    |   File "/app/calibre-web/cps/main.py", line 26, in main
calibre-web    |     app = create_app()
calibre-web    |   File "/app/calibre-web/cps/__init__.py", line 124, in create_app
calibre-web    |     updater_thread.start()
calibre-web    |   File "/usr/lib/python3.10/threading.py", line 935, in start
calibre-web    |     _start_new_thread(self._bootstrap, ())
calibre-web    | RuntimeError: can't start new thread
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/app/calibre-web/cps.py", line 31, in <module>
calibre-web    |     main()
calibre-web    |   File "/app/calibre-web/cps/main.py", line 26, in main
calibre-web    |     app = create_app()
calibre-web    |   File "/app/calibre-web/cps/__init__.py", line 124, in create_app
calibre-web    |     updater_thread.start()
calibre-web    |   File "/usr/lib/python3.10/threading.py", line 935, in start
calibre-web    |     _start_new_thread(self._bootstrap, ())
calibre-web    | RuntimeError: can't start new thread
calibre-web    | Traceback (most recent call last):
calibre-web    |   File "/app/calibre-web/cps.py", line 31, in <module>
calibre-web    |     main()
calibre-web    |   File "/app/calibre-web/cps/main.py", line 26, in main
calibre-web    |     app = create_app()
calibre-web    |   File "/app/calibre-web/cps/__init__.py", line 124, in create_app
calibre-web    |     updater_thread.start()
calibre-web    |   File "/usr/lib/python3.10/threading.py", line 935, in start
calibre-web    |     _start_new_thread(self._bootstrap, ())
calibre-web    | RuntimeError: can't start new thread

Any help greatly appreciated.

**Comment by devilsangel360live** [comment]
+1 - same here. Any help is greatly appreciated

**Comment by thespad** [comment]
https://docs.linuxserver.io/faq#jammy

**Comment by airdogvan** [comment]
Thanks so much I chose the short term option for the moment and that works fine.
Sorry that I didn't read the FAQ but they're not, that I can see, referenced on the git page.

**Comment by devilsangel360live** [comment]
Brilliant - thanks! Went with reinstalling docker on OMV and the latest 20.10 engine was pulled. It now works without issues
