### ISSUE TITLE
Deploy Docker Calibreweb

### ISSUE THREAD

**Issue by FlavioDF** [linuxserver/docker-calibre-web#219]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. Linux
2.
3.
4.

## Environment
**OS:*Linux*
**CPU architecture:** x86_64
**How docker service was installed:**

Docker Compose Code:
version: '3'

networks:
  net_infra:
    external:
      name: dnscrypt_net_infra
  default:
    driver: bridge

services:
  calibre-web-books:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web-books
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Sao_Paulo
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      #- DOCKER_MODS=linuxserver/calibre-web:calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
      #- GUAC_USER=flavio
      #- GUAC_PASS=10a9c136d796bab18d3e144092a4f20a
    volumes:
      - /volume2/docker/calibre-web/config:/config
      - /volume2/docker/calibre-web/books:/books
      - /volume2/docker/calibre-web/tmp:/tmp
      - /volume2/docker/calibre-web/config/gmail.json:/app/calibre-web/gmail.json
    ports:
      - 8083:8083
    restart: unless-stopped
    networks:
     net_infra:
         ipv4_address: 172.20.10.10
    cap_add:
      - NET_ADMIN

## Docker logs

Failed to import PyQt module: PyQt6.QtWebEngineCore with error: libXtst.so.6: cannot open shared object file: No such file or directory
Creating symlinks...
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________
	Traceback (most recent call last):
	  File "calibre/linux.py", line 831, in setup_completion
	  File "calibre/linux.py", line 574, in write_completion
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/main.py", line 15, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/ui.py", line 29, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/annotations.py", line 13, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/web_view.py", line 14, in <module>
	ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)
Setting up desktop integration...
____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________
	Traceback (most recent call last):
	  File "calibre/linux.py", line 852, in setup_desktop_integration
	  File "calibre/linux.py", line 874, in do_setup_desktop_integration
	  File "calibre/linux.py", line 905, in install_xdg_junk
	  File "calibre/linux.py", line 890, in install_icons
	  File "calibre/linux.py", line 884, in install_single_icon
	  File "subprocess.py", line 364, in check_call
	  File "subprocess.py", line 345, in call
	  File "subprocess.py", line 966, in __init__
	  File "subprocess.py", line 1842, in _execute_child
	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'
Creating un-installer: /usr/bin/calibre-uninstall
There were 2 warnings
* Setting up completion failed with error:
* Setting up desktop integration failed with error:
[custom-init] No custom files found, skipping...
[ls.io-init] done.
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1865]

**Comment by Roxedus** [comment]
Need more info. Ie kernel version and distro

**Comment by FlavioDF** [comment]
Linux NASFC1821 4.4.180+ #42962 SMP Tue Oct 18 15:02:09 CST 2022 x86_64 GNU/Linux synology_v1000_1821+

**Comment by shadowking001** [comment]
Same problem on Debian 11 here :

Linux srv-debian 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

**Comment by FlavioDF** [comment]
The conntainer was missing some dependencies.

run it into conntainer

docker exec -it yourconntainer /bin/bash


apt update; apt upgrade libgl1-mesa-glx libxdamage1 libegl1 libxkbcommon0 libopengl0 -y
apt-get install ghostscript -y
apt-get install -y python3-apscheduler
pip3 install -r /app/calibre-web/requirements.txt
pip3 install -r /app/calibre-web/optional-requirements.txt

**Comment by Ramblurr** [comment]
Can confirm.. this image is broken!

Running on a CentOS Stream 9 host with podman

**Comment by wadefelix** [comment]
> `ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)`

see https://github.com/kovidgoyal/calibre/blob/8b71e251c4b3bd1d05b22a1d129ccdd87ef2eac5/src/calibre/linux.py#L882
calibre will install some icons to the DESKTOP environment, BUT there is no desktop in the container.

Create dummy files to bypass it
```bash
RUN echo '#!/bin/sh' > /usr/bin/xdg-icon-resource && chmod +x /usr/bin/xdg-icon-resource \
 && echo '#!/bin/sh' > /usr/bin/xdg-desktop-menu && chmod +x /usr/bin/xdg-desktop-menu \
 && echo '#!/bin/sh' > /usr/bin/xdg-mime && chmod +x /usr/bin/xdg-mime
```

**Comment by Ramblurr** [comment]
Not stale! Still affected

**Comment by thespad** [comment]
The container runs just fine. There *is* an error output during startup if you're using the calibre mod due to it being unable to install the DE components but it doesn't stop the container from working. If you really want to suppress it, you can follow the instructions from https://github.com/linuxserver/docker-calibre-web/issues/219#issuecomment-1435559765

I've even tested it with rootless docker and it works (note that we don't test with, or support, podman - rootless or otherwise).

If you have a specific issue running the image, please open a new issue and actually provide the requested diagnostic information so that we have some chance of troubleshooting, rather than just "me too"ing an existing issue.
