### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by thefunkygibbon** [linuxserver/docker-calibre-web#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by j0nnymoe** [comment]
Nope.

**Comment by CHBMB** [comment]
The docker image is updated weekly, how much more alive do you want it @thefunkygibbon?
