### ISSUE TITLE
Can't login on admin user.

### ISSUE THREAD

**Issue by oppsig** [linuxserver/docker-calibre-web#23]
Can not login on calibre with admin:admin123.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

 Ubuntu 18.04

 Log file: https://pastebin.com/6GPvkRRv
 No symbolic links on mounts.

**Comment by j0nnymoe** [comment]
Run command?

**Comment by oppsig** [comment]
Oh sorry, here it is.

`docker create --name calibre -p 8083:8083 -e PUID=1002 -e PGID=1002 -e TZ=oslo -v /etc/localtime:/etc/localtime:ro -v /files/docker/calibre:/config -v /home/kodi/bookspub:/books linuxserver/calibre-web`

`docker start calibre`

**Comment by tobbenb** [comment]
TZ=Oslo should be TZ="Europe/Oslo" Doubt that is the issue though.
Do you have a Calibre database in the /books mount? If not, I think calibre-web might behave like this.

**Comment by oppsig** [comment]
No database in the /books mount, the database is in the /config mount.

**Comment by CHBMB** [comment]
You need an existing Calibre database like it says in the readme

**Comment by oppsig** [comment]
Oh sorry, my bad. Will close this issue now.

**Comment by CHBMB** [comment]
No worries...
