### ISSUE TITLE
[BUG] Send to Ereader hangs at 0%

### ISSUE THREAD

**Issue by darkangelvenom** [linuxserver/docker-calibre-web#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I send to ereader, instead of sending to ereader, the task sits at 0% and 9 seconds run time.

### Expected Behavior

Should send the file to my ereader

### Steps To Reproduce

1. Select book with a compatible format
2. Select 'Send to ereader'
3. Book is sent to ereader

### Environment

```markdown
- OS: DSM 7.1.1-42962 Update 2
- How docker service was installed: Through the docker package
```

### CPU architecture

x86-64

### Docker creation

```bash
https://imgur.com/a/gEYURLM
```

### Container logs

```bash
https://pastebin.com/pd0rYmPP (too long to fit)
```

**Comment by quietsy** [comment]
Same issue as in https://github.com/linuxserver/docker-calibre-web/issues/222

**Comment by darkangelvenom** [comment]
@quietsy Please correct me if I'm wrong, but the linked issue seems to be different than the issue I am having. I am unable to send books to an ereader, and that issue seems to be about converting documents.

**Comment by quietsy** [comment]
@darkangelvenom It seems like the same issue by the error in the log
