### ISSUE TITLE
[BUG] Runtime error: Can't start new thread

### ISSUE THREAD

**Issue by fr0st-beard** [linuxserver/docker-calibre-web#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Url is inaccessible, giving me a 502 proxy error in the browser. 

When I check the logs in portainer, I see the following:

Traceback (most recent call last):

  File "/app/calibre-web/cps.py", line 31, in <module>

    main()

  File "/app/calibre-web/cps/main.py", line 26, in main

    app = create_app()

  File "/app/calibre-web/cps/__init__.py", line 124, in create_app

    updater_thread.start()

  File "/usr/lib/python3.10/threading.py", line 935, in start

    _start_new_thread(self._bootstrap, ())

RuntimeError: can't start new thread

### Expected Behavior

I should be able to go to the url, have it load, and log in to upload/read/download my books.

### Steps To Reproduce

1. Start the container using the following:
2. docker run -d \
  --name=calibre-web \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e DOCKER_MODS=linuxserver/mods:universal-calibre `#optional` \
  -e OAUTHLIB_RELAX_TOKEN_SCOPE=1 `#optional` \
  -p 8083:8083 \
  -v [VALID PATH]:/config \
  -v [VALID PATH]:/books \
  --restart unless-stopped \
  lscr.io/linuxserver/calibre-web:latest
3. I can't access it via the URL, the IP with the port, or even using curl on the host machine.
4. I have tried both Docker and Docker compose.
5. Up until I noticed today, it was working normally.

### Environment

```markdown
- OS:Debian 4.19.269-1
- How docker service was installed: Using the recommended method on this Github repo (detailed above and below)
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=calibre-web \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e DOCKER_MODS=linuxserver/mods:universal-calibre `#optional` \
  -e OAUTHLIB_RELAX_TOKEN_SCOPE=1 `#optional` \
  -p 8083:8083 \
  -v [VALID PATH]:/config \
  -v [VALID PATH]:/books \
  --restart unless-stopped \
  lscr.io/linuxserver/calibre-web:latest
```

### Container logs

```bash
Traceback (most recent call last):

  File "/app/calibre-web/cps.py", line 31, in <module>

    main()

  File "/app/calibre-web/cps/main.py", line 26, in main

    app = create_app()

  File "/app/calibre-web/cps/__init__.py", line 124, in create_app

    updater_thread.start()

  File "/usr/lib/python3.10/threading.py", line 935, in start

    _start_new_thread(self._bootstrap, ())

RuntimeError: can't start new thread
```

**Comment by aptalca** [comment]
https://docs.linuxserver.io/faq#jammy

**Comment by fr0st-beard** [comment]
Thanks for your help. Updating Docker solved it. Not sure how I had Docker installed on this machine, but it was way out of date and this helped me to clean it up. I appreciate the time and help. Thanks for all the work you do.
