### ISSUE TITLE
[FEAT] 请提供一个批量删除的功能

### ISSUE THREAD

**Issue by 54whui** [linuxserver/docker-calibre-web#235]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

请提供一个批量删除的功能，一个一个的删除太消耗了。

### Reason for change

请提供一个批量删除的功能，一个一个的删除太消耗了。

### Proposed code change

请提供一个批量删除的功能，一个一个的删除太消耗了。

**Comment by Roxedus** [comment]
English only.

**Comment by drizuid** [comment]
We just package calibre-web in the container, if you want batch-delete, you need to ask the upstream maintainer to add this feature.
