### ISSUE TITLE
[FEAT] Calibre docker mod as separate image with layers instead of startup install script.

### ISSUE THREAD

**Issue by ruifung** [linuxserver/docker-calibre-web#237]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Having the calibre layer be baked into an optional image that can be pulled (and cached) instead of having to redownload the calibre tgz from github every time, which, depending on how the network (and github releases) is feeling, may hang.

### Reason for change

Sometimes github releases just don't download for me at all, and it would be nice to not have to watch it reinstall all the dependencies and calibre everytime I recreate the container.

**Comment by aptalca** [comment]
It shouldn't download anything every time or after a restart. Only after recreation

**Comment by ruifung** [comment]
I specifically meant after container recreation though. i.e  it's been recreated because I changed something in the compose file, for example.

**Comment by aptalca** [comment]
That's how all of our mods are designed to work

**Comment by ruifung** [comment]
Oh well. I guess it's fine, I've built my own modified image using github actions / renovatebot / ghcr to include calibre into the image itself.

If anyone stumbles across this in the future and is looking for something similar:

https://github.com/ruifung/lsio-calibre-web-mod

**Comment by Roxedus** [comment]
Also to anyone stumbling over this, we do not support using this image.
