### ISSUE TITLE
Missing "Send to Device" button for single book

### ISSUE THREAD

**Issue by figlizzard12** [linuxserver/docker-calibre-web#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All other books in library have the "Send to Device" button available and working, but most recent book doesn't. 

Same file format as the others, both epub and mobi, still nothing showing though. 

### Expected Behavior

Should have the option to send the book to a device. 

### Steps To Reproduce

Open the book from library - try to send book, unable to. 

### Environment

```markdown
- OS: Unraid OS
- How docker service was installed: using built-in docker for Unraid.
```

### CPU architecture

x86-64

### Docker creation

```bash
command not used.
```

### Container logs

```bash
no output
```

**Comment by 9acca9** [comment]
Did you find a solution to this? i dont see the send to device neither.
Thanks.

**Comment by figlizzard12** [comment]
I deleted the files that I had download and searched for another version. This one uploaded fine and now has the button available. 

It's still EPUB but a much smaller file, so not sure why this one worked. Maybe keep looking for different downloads.

**Comment by drizuid** [comment]
if anything this is an application issue, not a container issue. As such, it needs to be opened with the upstream dev's project. That said, not all books/formats have the same capabilities in the system. I believe the calibre-web wiki goes into some detail about this. tl;dr, it's not a bug.
