### ISSUE TITLE
[BUG] lsiown on /app/calibre-web extremely slow

### ISSUE THREAD

**Issue by leolivier** [linuxserver/docker-calibre-web#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting the container on a raspberrypi for the 1rst time, the lsiown cmd on /app/calibre-web is extremely slow (more than 10' !).
It was so slow I tried myself to run in parallel the command `chown -R abc:abc /app/calibre-web` and I saw it too more than 2secs per file. Looking for that on Internet, I found that: https://github.com/docker/for-linux/issues/388 

Why not changing the ownership in the Dockerfile instead?

### Expected Behavior

Fast start, even for the 1rst time 

### Steps To Reproduce

Just start calibre-web for the 1rst time and see how slow the lsiown is

### Environment

```markdown
- OS: raspberrypi OS (debian/bullseye)
- How docker service was installed: deb package
```

### CPU architecture

arm64

### Docker creation

```bash
---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
      - /hdd/nextcloud/olivier/files/Books:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment]
> Why not changing the ownership in the Dockerfile instead?

Because:
1) it's a cow issue and happens the first time the container is started
2) you set the PUID/PGID during runtime

**Comment by leolivier** [comment]
Thanks for your answer @aptalca 
It happens each time you recreate the container so at least for each new version.
But you're perfectly right, the puid, pgid are set by the user. Actually, what would be the risk of not setting them ?

**Comment by drizuid** [comment]
https://github.com/linuxserver/docker-calibre-web/pull/246 should resolve the superfluous chown on /app/calibre-web.  it will not resolve the cow issue your system faces though.

**Comment by leolivier** [comment]
Great, thanks!
For the copy on write part, I don't see any reason why we should write into the container internal storage. The issue seemed to appear only with this chown as far as I can see. As the /config is mounted on a specific directory which is not removed in case of recreation of the container, there shouldn't be any problem anymore.
