### ISSUE TITLE
[BUG] not email

### ISSUE THREAD

**Issue by xiangfeigao** [linuxserver/docker-calibre-web#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

why can not post email？  error，then error。please fix it

### Expected Behavior

 can not post email

### Steps To Reproduce

docker in debian 11

### Environment

```markdown
- OS:debian 11
- How docker service was installed:
docker is right，calibre run well，but can not post email。
```

### CPU architecture

x86-64

### Docker creation

```bash
no problem
```

### Container logs

```bash
no problem
```

**Comment by drizuid** [comment]
i'm just going to close this.. if you want us to fix something, provide relevant details. You can start by actually filling out the issue template.
