### ISSUE TITLE
[FEAT] Support for robots.txt file

### ISSUE THREAD

**Issue by manolitto** [linuxserver/docker-calibre-web#254]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

- A publicly available site using docker-calibre-web is getting indexed by search engines. This might be an unexpected and unwanted side-effect.
- calibre-web supports the use of a custom robots.txt file: see https://github.com/janeczku/calibre-web/wiki/Extend-Features#use-your-own-robotstxt-file

Proposed feature: Support for providing an external custom robots.txt

### Reason for change

Currently there is no way to use a (custom) robots.txt file with docker-calibre-web without modifying the docker content.

### Proposed code change

Proposed default robots.txt:
The docker-calibre-web container might already contain a default robots.txt file with the following content (to prevent unexpected indexing):
```
User-agent: *
Disallow: /

```

**Comment by rloomans** [comment]
One work-around for this is to add the file into the container manually.

If you are using docker compose, add the following to your docker-compose.yml after creating the robots.txt file:
```
      - ./robots.txt:/app/calibre-web/cps/static/robots.txt:ro
```

**Comment by drizuid** [comment]
This would be a nice universal docker mod if someone would like to make it.
https://docs.linuxserver.io/general/container-customization
