### ISSUE TITLE
 [FEAT] Update/Personalize favicon

### ISSUE THREAD

**Issue by jrhedman** [linuxserver/docker-calibre-web#265]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I'd love it if we could update the favicon to our own image/ico file.

### Reason for change

I think this would help increase personalization of calibre-web, similar to how we can update the website's title.

**Comment by aptalca** [comment]
That's really a request for the upstream project

**Comment by jrhedman** [comment]
> That's really a request for the upstream project

Linuxserver uses [this](https://github.com/janeczku/calibre-web) project then right?

It did find [this issue](https://github.com/janeczku/calibre-web/issues/1552) where they mentioned they'd rather have people update the file manually. But from my basic understanding of how docker works, if I update my image, then these changes would be overwritten wouldn't they?

**Comment by aptalca** [comment]
They would be.

Here are some ways to make them permanent:
https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers
