### ISSUE TITLE
[BUG] latest version not starting

### ISSUE THREAD

**Issue by adoucette** [linuxserver/docker-calibre-web#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting the latest version crashes with some Python errors, below.

`
Calibre-Web
500 Internal Server Error
The server encountered an internal error and was unable to complete your request. There is an error in the application.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1519, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/app/calibre-web/cps/usermanagement.py", line 35, in decorated_view
return login_required(func)(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
File "/app/calibre-web/cps/web.py", line 790, in index
return render_books_list("newest", sort_param, 1, page)
File "/app/calibre-web/cps/web.py", line 408, in render_books_list
entries, random, pagination = calibre_db.fill_indexpage(page, 0, db.Books, True, order[0],
File "/app/calibre-web/cps/db.py", line 782, in fill_indexpage
return self.fill_indexpage_with_archived_books(page, database, pagesize, db_filter, order, False,
File "/app/calibre-web/cps/db.py", line 789, in fill_indexpage_with_archived_books
random_query = self.generate_linked_query(config_read_column, database)
File "/app/calibre-web/cps/db.py", line 743, in generate_linked_query
query = (self.session.query(database, ub.ArchivedBook.is_archived, ub.ReadBook.read_status)
AttributeError: 'NoneType' object has no attribute 'query'`

### Expected Behavior

It used to just work brilliantly - now I can't get it started

### Steps To Reproduce

Running as docker on Unraid using default build, all default paths from container, setting only the books directory to the location of calibre's metadata.db file.

### Environment

```markdown
- OS:Unraid  Version: 6.11.5
- How docker service was installed: Using Unraid App Center version 2023.07.03
```

### CPU architecture

x86-64

### Docker creation

```bash
installed using Unraid App Center version 2023.07.03, used all default paths from container, setting only the books directory to the location of calibre's metadata.db file.
```

### Container logs

```bash
text  error  warn  system  array  login  

        Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
        Symlinking /app/calibre/web2disk to /usr/bin/web2disk
        Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
        Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
        Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
        Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
        Symlinking /app/calibre/calibredb to /usr/bin/calibredb
        Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
        Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
        Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
        Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
        Symlinking /app/calibre/calibre to /usr/bin/calibre
        Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
        Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
        Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/
Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


        Traceback (most recent call last):
          File "calibre/linux.py", line 858, in setup_desktop_integration
          File "calibre/linux.py", line 880, in do_setup_desktop_integration
          File "calibre/linux.py", line 911, in install_xdg_junk
          File "calibre/linux.py", line 896, in install_icons
          File "calibre/linux.py", line 890, in install_single_icon
          File "subprocess.py", line 364, in check_call
          File "subprocess.py", line 345, in call
          File "subprocess.py", line 966, in __init__
          File "subprocess.py", line 1842, in _execute_child
        FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

Creating un-installer: /usr/bin/calibre-uninstall


There were 1 warnings

* Setting up desktop integration failed with error:

[custom-init] No custom files found, skipping...
[ls.io-init] done.
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-calibre to container
[mod-init] linuxserver/mods:universal-calibre at sha256:8740df3342812152e5fa06fce2eff629189a91dfe2f8037e272b982cbabc5e8c has been previously applied skipping
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

**** Adding calibre dependencies to package install list ****
[mod-init] **** Installing all mod packages ****
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
libxdamage1 is already the newest version (1:1.1.5-2build2).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
**** Calibre already installed, skipping ****
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by kevindherdt** [comment]
I am having the exact same error but on mac1 aarch64 version. I tried installing older versions but I keep getting same error now.

**Comment by psanf** [comment]
I'm having exactly the same issue on Ubuntu 22.04.3 LTS.
Any idea on how to fix this?

**Comment by drizuid** [comment]
closing as OP and subsequent users didn't fully fill out the issue template which prevents us from attempting to recreate the issue.  We need to see how the container was created, as clearly stated in the template.

As a note for the others, there is never a situation where "Exact same issue" is useful to anyone.

**Comment by adoucette** [comment]
I would fill that info in if you could tell me where to find it. I
installed it from thr Unraid app store

**Comment by gone** [comment]
confirming the app is currently borked after upgrading the version on unraid

**Comment by drizuid** [comment]
> confirming the app is currently borked after upgrading the version on unraid

your statement is not helpful or useful in any way.
