### ISSUE TITLE
[BUG] sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by MarGer1962** [linuxserver/docker-calibre-web#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used the taskmanager on my Nas Synology with this task

docker run -d --name=calibre-web \
-p 8083:8083 \
-e PUID=1024 \
-e PGID=100 \
-e TZ=Europe/Amsterdam \
-e DOCKER_MODS=linuxserver/mods:universal-calibre \
-e OAUTHLIB_RELAX_TOKEN_SCOPE=1 \
-v /volume1/docker/calibreweb:/config \
-v /volume1/Ebooks:/books \
--restart always \
ghcr.io/linuxserver/calibre-web
(following the instuctions on https://mariushosting.com/how-to-install-calibre-web-on-your-synology-nas/)

Calibre web was installed
It is adjusted as a container (linuxserver/calibre-web) in Docker

I was not able to open Calibre-web in my browser.
When i checked the logfile, i found this

===== begin 
sqlite3.OperationalError: unable to open database file
====== end > see Container Logs

### Expected Behavior

I would expect that calibre-web was functioning when opening the app in my browser

### Steps To Reproduce

NAS Synology DS716+
NAS / DSM 7.11 - 42962 Update 6
Python: installed 3.9
Docker

> make a Task in the Taskmanager
use this code

docker run -d --name=calibre-web \
-p 8083:8083 \
-e PUID=1024 \
-e PGID=100 \
-e TZ=Europe/Amsterdam \
-e DOCKER_MODS=linuxserver/mods:universal-calibre \
-e OAUTHLIB_RELAX_TOKEN_SCOPE=1 \
-v /volume1/docker/calibreweb:/config \
-v /volume1/Ebooks:/books \
--restart always \
ghcr.io/linuxserver/calibre-web

> run the task
> Calibre -web is installed
> check settings > OK
> check log > fault

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d --name=calibre-web \
-p 8083:8083 \
-e PUID=1024 \
-e PGID=100 \
-e TZ=Europe/Amsterdam \
-e DOCKER_MODS=linuxserver/mods:universal-calibre \
-e OAUTHLIB_RELAX_TOKEN_SCOPE=1 \
-v /volume1/docker/calibreweb:/config \
-v /volume1/Ebooks:/books \
--restart always \
ghcr.io/linuxserver/calibre-web
```

### Container logs

```bash
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/calibre-web/cps.py", line 31, in <module>
    main()
  File "/app/calibre-web/cps/main.py", line 31, in main
    app = create_app()
  File "/app/calibre-web/cps/__init__.py", line 115, in create_app
    ub.init_db(cli_param.settings_path)
  File "/app/calibre-web/cps/ub.py", line 838, in init_db
    Base.metadata.create_all(engine)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/schema.py", line 4930, in create_all
    bind._run_ddl_visitor(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3237, in _run_ddl_visitor
    with self.begin() as conn:
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3153, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
```

**Comment by MarGer1962** [comment]
![SettingsCalibre00a](https://github.com/linuxserver/docker-calibre-web/assets/77753615/242b32e9-6755-43de-9864-1a5420937b25)
![SettingsCalibre03](https://github.com/linuxserver/docker-calibre-web/assets/77753615/83ae9073-4a07-4bb2-a9a3-91bbad5e6346)
![SettingsCalibre00](https://github.com/linuxserver/docker-calibre-web/assets/77753615/34e3b6ca-3181-423a-9aea-e148210d3d0b)
![SettingsCalibre02](https://github.com/linuxserver/docker-calibre-web/assets/77753615/56209364-070c-48d8-a1e2-6eabe2b31a42)
![SettingsCalibre01](https://github.com/linuxserver/docker-calibre-web/assets/77753615/93c763f7-1357-416b-a437-3c644af2460c)

**Comment by drizuid** [comment]
you need a database, as it tells you...

**Comment by MarGer1962** [comment]
@drizuid : Thanks for your reply. 
I have a calibre db (metadata.db) on my local PC (D:\00.CalibreBieb)
I have this question(s):
> is this the database you refer to in your answer?
> how can i put the calibre db (metadata.db) on my NAS Synology? Can i just use Filemanager (copy/paste)?
> in which directory do i have to put the calibre db (metadata.db)?

Hopefully you can help me out

The reason for my questions: before i updated CalibreWeb everything was working fine.
After updating it was not possible to connect to CalibreWeb.
I did not (and do not) understand why that is. 
I thought the best solution was to remove all the books/the database and the container and make a fresh installation.

**Comment by drizuid** [comment]
It would be best for you to come into discord for support, your logs do not indicate a bug and we can more appropriately help you there.

As a note, WHERE the database should be is covered in the readme. Yes, metadata.db is the typical name, assuming it's a legitimate calibre database.

I have no other info for Synology as I don't use it. We have users on discord.

**Comment by ariael** [comment]
Hi,
I have same issue.
Maybe 50 different installation (Synology). And only 2 successful started web. Both runed only short time, first until restart docker and second live about 30 minute, until i try view book - web freeze and never start again...

I was try every combination with preinstalled books (and db), without books, different ports, different folders, privileges, different method of installation...
Sorry, i don't known how i should continue to...
Can you help me please?

i use mostly this YAML:
---
version: "2.1"
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Prague
      - DOCKER_MODS=linuxserver/mods:universal-calibre     #  optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1     #  optional
    volumes:
      - /volume1/docker/calibreweb:/config
      - /volume1/docker/calibreweb/books:/books
    ports:
      - 9999:9999
    restart: unless-stopped
    
I also have a CLI version for an older setup type. But same result.

**Comment by drizuid** [comment]
@ariael your ports are wrong, is your syno x86_64?  we only support docker-compose or docker from the cli, not the synology ui to create/deploy containers, is that how you are using it? fix your port and see if it works.

**Comment by ariael** [comment]
Hi. This is Intel Celeron CPU...

Port - well that's just the latest version of the experiment. From the default ones up to here, to exclude the possibility of some port occupation by another process or something strange in docker... The standard port doesn't work either, of course. And the portainer I use, CLI or directly Container Manager - they all behave the same. Docker is running, you can look inside, the directory with books is available, the database is visible, the web is dead.

**Comment by ariael** [comment]
<img width="1363" alt="image" src="https://github.com/linuxserver/docker-calibre-web/assets/26325215/da205b84-9d63-41f2-8859-b93bea1f63cc">

**Comment by ariael** [comment]
<img width="1458" alt="image" src="https://github.com/linuxserver/docker-calibre-web/assets/26325215/08987e7b-a534-42f0-8d95-89f725aeef24">

**Comment by ariael** [comment]
<img width="976" alt="image" src="https://github.com/linuxserver/docker-calibre-web/assets/26325215/3ba9cd11-410f-4a76-b6fa-2d1f90d3c897">

**Comment by ariael** [comment]
Same with redeploy to 8083

**Comment by ariael** [comment]
And first setup i follow https://mariushosting.com/how-to-install-calibre-web-on-your-synology-nas/

docker run -d --name=calibre-web \
-p 8083:8083 \
-e PUID=1026 \
-e PGID=100 \
-e TZ=Europe/Bucharest \
-e DOCKER_MODS=linuxserver/mods:universal-calibre \
-e OAUTHLIB_RELAX_TOKEN_SCOPE=1 \
-v /volume1/docker/calibreweb:/config \
-v /volume1/web/books:/books \
--restart always \
ghcr.io/linuxserver/calibre-web

**Comment by thespad** [comment]
```
ports:
- 9999:9999
```
Will never work, regardless of what else you configure. Calibre-web runs on port 8083.

**Comment by ariael** [comment]
Oki,
I stop portainer (any interference), delete all old directory, create new, one, change port in YAML file to 8083 and use Docker Compose to build new image...
<img width="1105" alt="image" src="https://github.com/linuxserver/docker-calibre-web/assets/26325215/d1baa5ce-9175-46d8-bb63-ad271fe687f2">

<img width="766" alt="image" src="https://github.com/linuxserver/docker-calibre-web/assets/26325215/f2c791ca-de09-406d-b60b-829200111601">

<img width="959" alt="image" src="https://github.com/linuxserver/docker-calibre-web/assets/26325215/b094f713-262c-4741-ac55-9ced26501bbb">

<img width="882" alt="image" src="https://github.com/linuxserver/docker-calibre-web/assets/26325215/af085118-014a-4f88-b8a8-8f390c977e63">

**Comment by thespad** [comment]
Please provide your container logs.

But also don't do this
```
volumes:
- /volume1/docker/calibreweb:/config
- /volume1/docker/calibreweb/books:/books
```
You're making your /books directory a subfolder of your /config directory as well as mounting it to /books - sooner or later things are going to go wrong with that setup.

**Comment by drizuid** [comment]
also note that you say you're using compose but you keep showing us stuff from container station. we only want to see docker logs -f calibre-web and your docker compose. if you are using container station or portainer to deploy the container, it will not work.

**Comment by MarGer1962** [comment]
@thespad Adam
Hi you wrote "But also don't do this
volumes:
- /volume1/docker/calibreweb:/config
- /volume1/docker/calibreweb/books:/books

You're making your /books directory a subfolder of your /config directory as well as mounting it to /books - sooner or later things are going to go wrong with that setup."
I suppose that is a reaction to Aerieal who place a post with these lines
"-v /volume1/docker/calibreweb:/config
-v /volume1/web/books:/books "

I'm interested in what information do i have to put in these lines?
Should it be - if i place my ebooks in the directory /volume1/Ebooks
"-v /volume1/docker/calibreweb:/calibreweb
-v /volume1/Ebooks:/books"

Or should i place all of my ebooks in the directory /volume1/docker/calibreweb/Ebooks?
So then these lines should be:
"-v /volume1/docker/calibreweb:/calibreweb
-v /volume1/docker/calibreweb/Ebooks:/books"

**Comment by thespad** [comment]
You should always keep any given mount separate from any others. So either something like:
```
- /app/foo/config:/config
- /app/foo/data:/data
```
or
```
- /app/foo:/config
- /mnt/foo:/data
```
but never
```
- /app/foo:/config
- /app/foo/data:/data
```

**Comment by drizuid** [comment]
as ariael has moved to discord as requested, and this is not a container problem but a host problem, i will lock this thread. best effort help is available on discord.
