### ISSUE TITLE
Initial setup /books error

### ISSUE THREAD

**Issue by helpdt** [linuxserver/docker-calibre-web#28]
Hello,
I have a Problem to setting up the location on the initial setup screen. The GUI can't find the location of my calibre DB. I mounted my location on the NAS to /books on the Container.
![image](https://user-images.githubusercontent.com/46899347/51486227-6a7c1380-1da0-11e9-9b9c-01a6c10a7555.png)

In the Terminal I can see all my books under /books including the /books/metadata.db . 
![image](https://user-images.githubusercontent.com/46899347/51486009-d5791a80-1d9f-11e9-93ee-21f41df406ea.png)

When I'm now typing on the initial setup screen /books to the empty field I get an error message, that the path is wrong (DB Speicherort ist ungültig, bitte korrigieren Pfad korrigieren)
![image](https://user-images.githubusercontent.com/46899347/51486272-926b7700-1da0-11e9-9710-90ff93045770.png)
.

The protocoll shows me...: 
![image](https://user-images.githubusercontent.com/46899347/51485915-8f23bb80-1d9f-11e9-8058-56a5b4936a06.png)
  
The system is running with docker on a synology 718+. 

Thanks for your help
helpdt

**Comment by kolossboss** [comment]
+1 I have exact the same problem!
Running Docker on Synology Diskstation 416play.

**Comment by CHBMB** [comment]
It'll be permissions.  Neither of you have posted enough information to say for sure, but it'll be a combination of `PUID` `PGID` and your NFS mount.  Try running `ls -la` on your `/books` folder

**Comment by helpdt** [comment]
thanks for the fast answer, 
if i type "ls -la books/metadata.db" in the terminal i get the following information. 
![image](https://user-images.githubusercontent.com/46899347/51556663-1c880e00-1e7b-11e9-89d1-0bfd4f5728dc.png)

 if I set the permissions for all to rwx it's the same situation. 
![image](https://user-images.githubusercontent.com/46899347/51557933-83f38d00-1e7e-11e9-876a-333bc9abd100.png)

The initial setup screen doesn't work in this configuration.
 
can I try anything else?

**Comment by helpdt** [comment]
it works with "chmod -v 777 /books/" :) 
you've been right with the permission problem. Thanks for your support!

**Comment by Dinth** [comment]
Im struggling with this as well.
Im trying to run calibre-web with library located on a OMV volume. This means that permissions must be set to 2755 and ownership to root:users.
Ive been trying to run this container with uid/gid: 0:0 but no luck
