### ISSUE TITLE
Latest image (0.6.21) is missing /usr/bin/ebook-convert

### ISSUE THREAD

**Issue by asinwang** [linuxserver/docker-calibre-web#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Latest image (0.6.21) is missing /usr/bin/ebook-convert

### Steps To Reproduce

Latest image (0.6.21) is missing /usr/bin/ebook-convert

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

arm64

### Docker creation

```bash
Latest image (0.6.21) is missing /usr/bin/ebook-convert
```

### Container logs

```bash
Latest image (0.6.21) is missing /usr/bin/ebook-convert
```

**Comment by eloo** [comment]
@asinwang 
you need to add the docker_mod as env

```
- name: DOCKER_MODS
  value: linuxserver/mods:universal-calibre
```

this is also covered in the docs
