### ISSUE TITLE
[BUG] how to rebuild the idex/database

### ISSUE THREAD

**Issue by Ziglar1** [linuxserver/docker-calibre-web#288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, 
i have installed Calibre-web into a docker on synology. 
after i installed everything correctly i noticed that in my folder with books there were folders with only a cover.jpg and metafata.opf (this was my fault).
i ran a script to remove all folders that had only these files (Thousends of folders). 
although they are gone now and i have only folders with books, Calibre-web is still showing those books. 

how can i make Calibre-web check the existance of every folder or rebuild the entire index ?

(re-installing is not an option due to several kobo-readers syncing)

### Expected Behavior

a button to re-index the whole disk or check for removed books would be awsome

### Steps To Reproduce

Delete a book folder from hard drive
Restart Calibre-web
Book is still there with no information and no cover

### Environment

```markdown
- OS: Synology Docker
- How docker service was installed: using synology store
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d --name=calibre-web \
-p 8782:8083 \
-e PUID=1026 \
-e PGID=100 \
-e TZ=Europe/Amsterdam \
-e DOCKER_MODS=linuxserver/mods:universal-calibre \
-e OAUTHLIB_RELAX_TOKEN_SCOPE=1 \
-v /volume1/docker/calibreweb:/config \
-v /volume1/Media/Media/Boeken:/books \
--restart always \
ghcr.io/linuxserver/calibre-web
```

### Container logs

```bash
No Need
```

**Comment by homerr** [comment]
Unfortunately this isn't something we can answer. I'd recommend speaking to the calibre-web devs and going from there, or trying to repair the databases with the desktop version before bringing an updated database back online.
