### ISSUE TITLE
Use multiple libraries with Calibreweb

### ISSUE THREAD

**Issue by HollyGhos** [linuxserver/docker-calibre-web#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io
I'm using multiple libraries within my desktop calibre
Maybe I missed it but could not find an easy way to change between libraries in calibreweb. Is this already implemented?

Thanks
Holger

**Comment by j0nnymoe** [comment]
This probably should be asked here: https://github.com/janeczku/calibre-web.
