### ISSUE TITLE
[BUG] needs gevent installed

### ISSUE THREAD

**Issue by rcludwick** [linuxserver/docker-calibre-web#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fetch metadata breaks the container.  This is a known problem with calibre-web.

https://github.com/janeczku/calibre-web/issues/2963
https://github.com/janeczku/calibre-web/issues/2719

Fix is to install gevent into virtual envb.

### Expected Behavior

Calibre-web should not hang.

### Steps To Reproduce

Upload a book.
Fetch metadata
See it hang
Try to connect to it again, and it fails to connect.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed:  docker compose.
```

### CPU architecture

x86-64

### Docker creation

```bash
Used the same as specified in the linuxserver.io's docs.
```

### Container logs

```bash
calibre  | [mod-init] Running Docker Modification Logic
calibre  | [mod-init] Adding linuxserver/calibre-web:calibre to container
calibre  | [mod-init] Downloading linuxserver/calibre-web:calibre from lscr.io
calibre  | [mod-init] (ERROR) Invalid tarball, could not download linuxserver/calibre-web:calibre from lscr.io
calibre  | [migrations] started
calibre  | [migrations] no migrations found
calibre  | ───────────────────────────────────────
calibre  | 
calibre  |       ██╗     ███████╗██╗ ██████╗
calibre  |       ██║     ██╔════╝██║██╔═══██╗
calibre  |       ██║     ███████╗██║██║   ██║
calibre  |       ██║     ╚════██║██║██║   ██║
calibre  |       ███████╗███████║██║╚██████╔╝
calibre  |       ╚══════╝╚══════╝╚═╝ ╚═════╝
calibre  | 
calibre  |    Brought to you by linuxserver.io
calibre  | ───────────────────────────────────────
calibre  | 
calibre  | To support LSIO projects visit:
calibre  | https://www.linuxserver.io/donate/
calibre  | 
calibre  | ───────────────────────────────────────
calibre  | GID/UID
calibre  | ───────────────────────────────────────
calibre  | 
calibre  | User UID:    1000
calibre  | User GID:    1000
calibre  | ───────────────────────────────────────
calibre  | 
calibre  | [custom-init] No custom files found, skipping...
calibre  | [ls.io-init] done.
```

**Comment by bujesse** [comment]
I am also seeing this behavior. However when I look in the container, gevent does seem to be installed. [This](https://github.com/janeczku/calibre-web/issues/2719) issue appears to have been updated to a different error entirely; Amazon apparently blocking requests. I will monitor both issues.

**Comment by rcludwick** [comment]
It is weird that when it happens it shuts down every thing running in the
docker container.

The Amazon error, and the the Amazon error shouldn't stop the web server
from serving requests.
