### ISSUE TITLE
Could audible reading be added? Can audible reading be increased?[FEAT] <title>

### ISSUE THREAD

**Issue by janewar** [linuxserver/docker-calibre-web#297]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Could audible reading be added?
Can audible reading be increased?

### Reason for change

Could audible reading be added?
Can audible reading be increased?

### Proposed code change

Could audible reading be added?
Can audible reading be increased?

**Comment by janewar** [comment]
Could audible reading be added?
Can audible reading be increased?

**Comment by janewar** [comment]
Can AI plus e-books be turned into audiobooks?

Or even use AI to summarize the content of e-books

**Comment by janewar** [comment]
Can the TTS function for online reading be added?

**Comment by Roxedus** [comment]
This sounds like something you want to ask calibre-web directly. This repo is for issues with the docker image.
