### ISSUE TITLE
I can't use E-Book Converter after update 0..6.22[BUG] <title>

### ISSUE THREAD

**Issue by xtuzwl** [linuxserver/docker-calibre-web#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After I update calibre-web to 0.6.22, I can't use E-Book Converter now, there isn't "Path to Calibre E-Book Converter" setting, who can help me?

### Steps To Reproduce

![截屏2024-07-13 00 04 07](https://github.com/user-attachments/assets/ba5737ba-244b-4220-b39d-f44e8a345af1)

### Environment

```markdown
- OS:Synology DSM 7.2.1-69057 Update 5
- How docker service was installed: reinstalled a new version via docker run: docker pull lscr.io/linuxserver/calibre-web:latest
```

### CPU architecture

x86-64

### Docker creation

```bash
docker pull lscr.io/linuxserver/calibre-web:latest

create docker container use synology container manager
```

### Container logs

```bash
date	stream	content
2024/07/12 23:34:32	stdout	[ls.io-init] done.
2024/07/12 23:34:21	stdout	[custom-init] No custom files found, skipping...
2024/07/12 23:34:21	stdout	**** Calibre already installed, skipping ****
2024/07/12 23:34:21	stdout	0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
2024/07/12 23:34:20	stdout	libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.2).
2024/07/12 23:34:20	stdout	libxdamage1 is already the newest version (1:1.1.5-2build2).
2024/07/12 23:34:20	stdout	Reading state information... 0%  Reading state information... 0% Reading state information... Done
2024/07/12 23:34:20	stdout	Building dependency tree... 0% Building dependency tree... 0% Building dependency tree... 50% Building dependency tree... 50% Building dependency tree... 95% Building dependency tree... Done
2024/07/12 23:34:19	stdout	Reading package lists... 0% Reading package lists... 0% Reading package lists... 0% Reading package lists... 5% Reading package lists... 5% Reading package lists... 5% Reading package lists... 5% Reading package lists... 18% Reading package lists... 40% Reading package lists... 55% Reading package lists... 55% Reading package lists... 56% Reading package lists... 56% Reading package lists... 60% Reading package lists... 64% Reading package lists... 64% Reading package lists... 74% Reading package lists... 74% Reading package lists... 78% Reading package lists... 78% Reading package lists... 79% Reading package lists... 79% Reading package lists... 85% Reading package lists... 85% Reading package lists... 86% Reading package lists... 95% Reading package lists... 95% Reading package lists... 99% Reading package lists... 99% Reading package lists... 99% Reading package lists... 99% Reading package lists... Done
2024/07/12 23:34:16	stdout	                         0% [Working] 20% [Working]               Reading package lists... 0% Reading package lists... 0% Reading package lists... 0% Reading package lists... 5% Reading package lists... 5% Reading package lists... 5% Reading package lists... 5% Reading package lists... 18% Reading package lists... 40% Reading package lists... 55% Reading package lists... 55% Reading package lists... 56% Reading package lists... 56% Reading package lists... 60% Reading package lists... 64% Reading package lists... 64% Reading package lists... 74% Reading package lists... 74% Reading package lists... 78% Reading package lists... 78% Reading package lists... 79% Reading package lists... 79% Reading package lists... 85% Reading package lists... 85% Reading package lists... 87% Reading package lists... 95% Reading package lists... 95% Reading package lists... 99% Reading package lists... 99% Reading package lists... 99% Reading package lists... 99% Reading package lists... Done
2024/07/12 23:34:13	stdout	                         0% [Working] 0% [Waiting for headers]                          Hit:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease
2024/07/12 23:34:12	stdout	                         0% [Working] 0% [Waiting for headers]                          Hit:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
2024/07/12 23:34:12	stdout	0% [Working] 0% [Waiting for headers]                          Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
2024/07/12 23:34:11	stdout	[pkg-install-init] **** Installing all mod packages ****
2024/07/12 23:34:11	stdout	**** Adding calibre dependencies to package install list ****
2024/07/12 23:34:11	stdout	
2024/07/12 23:34:11	stdout	───────────────────────────────────────
2024/07/12 23:34:11	stdout	User GID:    911
2024/07/12 23:34:11	stdout	User UID:    911
2024/07/12 23:34:11	stdout	
2024/07/12 23:34:11	stdout	───────────────────────────────────────
2024/07/12 23:34:11	stdout	GID/UID
2024/07/12 23:34:11	stdout	───────────────────────────────────────
2024/07/12 23:34:11	stdout	
2024/07/12 23:34:11	stdout	https://www.linuxserver.io/donate/
2024/07/12 23:34:11	stdout	To support LSIO projects visit:
2024/07/12 23:34:11	stdout	
2024/07/12 23:34:11	stdout	───────────────────────────────────────
2024/07/12 23:34:11	stdout	   Brought to you by linuxserver.io
2024/07/12 23:34:11	stdout	
2024/07/12 23:34:11	stdout	      ╚══════╝╚══════╝╚═╝ ╚═════╝
2024/07/12 23:34:11	stdout	      ███████╗███████║██║╚██████╔╝
2024/07/12 23:34:11	stdout	      ██║     ╚════██║██║██║   ██║
2024/07/12 23:34:11	stdout	      ██║     ███████╗██║██║   ██║
2024/07/12 23:34:11	stdout	      ██║     ██╔════╝██║██╔═══██╗
2024/07/12 23:34:11	stdout	      ██╗     ███████╗██╗ ██████╗
2024/07/12 23:34:11	stdout	
2024/07/12 23:34:11	stdout	───────────────────────────────────────
2024/07/12 23:34:11	stdout	usermod: no changes
2024/07/12 23:34:11	stdout	[migrations] no migrations found
2024/07/12 23:34:11	stdout	[migrations] started
```

**Comment by aptalca** [comment]
It's in the screenshot
`Path to Calibre Binaries`

**Comment by majiesg** [comment]
/usr/bin/X11

**Comment by daithi-coyle** [comment]
I am also having this issue.

@aptalca  As you can see in the OP screenshot, there's a field where a path can be typed, but there is no folder icon on the side. I think that might be a symptom?

Running Unraid 6.12
lscr.io/linuxserver/calibre-web
0.6.22 - e9bccc83c54a810078ff54dd157ddc5d8d4cd163 - 2024-07-06T13:29:17+02:00

Docker Run Command when I force update the container shows the variable
<img width="896" alt="runcmd" src="https://github.com/user-attachments/assets/ad1b340c-6969-423c-835e-15983e1a1425">

In the External Binaries section I have added both the converter and kepubify
<img width="662" alt="extbin" src="https://github.com/user-attachments/assets/5fe469ed-4b0d-486f-9035-82f7b6c97a92">

The About page shows kepubify version but converter says not installed
<img width="367" alt="installed" src="https://github.com/user-attachments/assets/8808964c-a888-4a2c-90e9-44f1443c6e08">

Opening a book I can convert to kepub (using kepubify obviously) not not any other format
<img width="248" alt="convert" src="https://github.com/user-attachments/assets/e37be30e-bc99-4b63-b0cf-bbd0ce3f9a37">

**Comment by daithi-coyle** [comment]
Lesson to self not to try and troubleshoot before bed.
I had the path in _Converter Settings_ not _Path to Binaries_. Spotted it right away this morning.

That said, [Github Page](https://github.com/linuxserver/docker-calibre-web?tab=readme-ov-file#application-setup) says to use _/usr/bin/ebook-convert_ which doesn't work. _/usr/bin/X11_ as mentioned by majiesg does.

**Comment by mistrello96** [comment]
I encountered the same problem and the solution proposed by @majiesg fixes the proplem. I think the mantainer should update the README cause it is quite misleading as now

**Comment by thespad** [comment]
`/usr/bin/X11` is a symlink to `/usr/bin`
```
lrwxrwxrwx 1 root root          1 Mar 25  2022  X11 -> .
```
If you want to be *really* pedantic the path is actually `/app/calibre/ebook-convert` it's just that the installer symlinks it to `/usr/bin/ebook-convert` (for which `/usr/bin/X11/ebook-convert` will obviously also work, because it's a symlink)

**Comment by aptalca** [comment]
Just created a container with `docker run -d --rm --name test -e DOCKER_MODS=linuxserver/mods:universal-calibre ghcr.io/linuxserver/calibre-web`
and I get
```
$ docker exec test ls -al /usr/bin/ebook-convert
lrwxrwxrwx 1 root root 26 Jul 25 23:31 /usr/bin/ebook-convert -> /app/calibre/ebook-convert
```
Our readme is correct and all the calibre binaries are under `/usr/bin`

**Comment by aptalca** [comment]
It's already in the readme.

Not sure what you mean by `Every time I fill in /usr/bin, it says that it does not contain the required file.`. To my knowledge no one reported that before. If that's a legitimate error you're getting in calibre-web, please let calibre-web know.

**Comment by a3205910682** [comment]
![image](https://github.com/user-attachments/assets/1612f570-3a5d-4736-a5d4-3da71eb94fde)
![image](https://github.com/user-attachments/assets/95747514-c03b-4fb1-bfc6-13999a9ba165)
As shown in the picture, 
When I directly fill in /usr/bin according to picture 1
It will appear
`
Missing calibre binaries: ebook-convert, calibredb, Missing executable permissions: ebook-convert, calibredb`

I only follow
> /usr/bin/X11
Fill in /usr/bin/x11
To successfully identify /usr/bin

I don't know much about Linux, maybe this is my mistake?
If it's not my mistake, who should I report it to?

**Comment by aptalca** [comment]
I can't reproduce it. I just created a fresh calibre-web container with the mod enabled and with a blank db. Went into settings, hit the folder icon for selecting binary path, browsed to `/usr/bin` and hitselect then save. Got the message `Calibre-Web configuration updated`. No errors.

**Comment by minermartijn** [comment]
> `/usr/bin/X11` is a symlink to `/usr/bin`
> 
> ```
> lrwxrwxrwx 1 root root          1 Mar 25  2022  X11 -> .
> ```
> 
> If you want to be _really_ pedantic the path is actually `/app/calibre/ebook-convert` it's just that the installer symlinks it to `/usr/bin/ebook-convert` (for which `/usr/bin/X11/ebook-convert` will obviously also work, because it's a symlink)

Everything i tried didnt work.
Adding the path /app/calibre/ fixed it for me! Thanks @thespad
