### ISSUE TITLE
Google Drive integration issue & fix

### ISSUE THREAD

**Issue by jobcurtis** [linuxserver/docker-calibre-web#31]
Issue: When setting up Google Drive integration, calibre-web can't find the client_secrets.json file.

Fix: `docker exec -it calibre-web ln -s /config/client_secrets.json /app/calibre-web/client_secrets.json`

Presumably this could be a permanent fix in https://github.com/linuxserver/docker-calibre-web/blob/master/root/etc/cont-init.d/30-config, but I don't know enough about docker to submit a pull request.

**Comment by CHBMB** [comment]
Closed by https://github.com/linuxserver/docker-calibre-web/pull/41
