### ISSUE TITLE
[BUG] Deleting book 4 failed, path [ some-directory has subfolders: ['@eaDir']

### ISSUE THREAD

**Issue by venuses** [linuxserver/docker-calibre-web#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I deployed the latest docker version of caliber-web on synology. When deleting books, I cannot delete the hidden directory on the NAS.

### Expected Behavior

delete directory successfully

### Steps To Reproduce

docker image version: 0.6.23
add a book,and then delete it on calibre web ui,this error appears in the calibre-web.log directory。
like this:
[2024-08-07 21:29:28,253]  WARN {cps.helper:372} Deleting book 5 failed, path a-directory(5) has subfolders: ['@eaDir']
[2024-08-07 21:29:32,802]  WARN {cps.helper:372} Deleting book 4 failed, path a-directory (4) has subfolders: ['@eaDir']

Check the @eaDir directory permissions on the terminal

```
ls -alh
drwxrwxrwx+ 1 root  users  74 Aug  7 21:23 @eaDir
```

### Environment

```markdown
- OS: DSM 7.2.1-69057 Update 5
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
services:
  calibre:
    image: linuxserver/calibre-web:0.6.23
    container_name: calibre
    restart: unless-stopped
    environment:
      - "TZ=Asia/Shanghai"
      - PUID=1027
      - PGID=100
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - '/volume1/docker/calibre/config:/config'
      - /volume1/document/calibre:/books
      - /volume1/docker/calibre/metadata_provider:/app/calibre-web/cps/metadata_provider
```

### Container logs

```bash
no logs
```

**Comment by j0nnymoe** [comment]
It's part of NAS and not supposed to be deleted.
