### ISSUE TITLE
<title>ebpb格式图书，左右显示占比太小，如何调整？

### ISSUE THREAD

**Issue by star2k** [linuxserver/docker-calibre-web#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/800a337b-50f9-4016-8603-f76a3a888e19)
显示界面有一大批空白，如何修改，提高显示占比？

### Expected Behavior

如题

### Steps To Reproduce

如题

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
如题
```

### Container logs

```bash
如题
```

**Comment by thelamer** [comment]
Closing https://github.com/janeczku/calibre-web/issues/3164
we do not write the code for the app just package it up in a container.
