### ISSUE TITLE
[FEAT] hope preview mobi

### ISSUE THREAD

**Issue by AbelKeithsun** [linuxserver/docker-calibre-web#322]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

hope preview mobi

### Reason for change

hope preview mobi

**Comment by AbelKeithsun** [comment]
Please forgive my poor English writing skills.I hope that the Docker version of Calibre-Web will have the capability to preview MOBI format files.

**Comment by j0nnymoe** [comment]
If this is a feature request for calibre-web, it needs to be reported to them. If this is already a feature of calibre-web but not working within the container, you need to give us some error logs.

**Comment by drizuid** [comment]
OP, we are not the devs of calibre-web, feature requests would go to them. We simply package their application in a container. Closing this as out of scope.
