### ISSUE TITLE
[FEAT] Rapid API Goodreads Books Feature Request

### ISSUE THREAD

**Issue by byertsy** [linuxserver/docker-calibre-web#326]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Are we likely to see the option to use rapid APIs goodbreads books API?
https://rapidapi.com/valengguerra@gmail.com/api/goodreads-books/

### Reason for change

Goodreads API shutdown in 2020 and has not been replaced. This is a viable alternative option.

**Comment by Roxedus** [comment]
This is a request for upstream, we do not develop calibre-web.
