### ISSUE TITLE
[BUG] pip not installed so docker image incomplete

### ISSUE THREAD

**Issue by banksonian** [linuxserver/docker-calibre-web#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

logs show a persistent error looking for the Flask package and web site is inaccessible (not running)

Instance fixed by:
docker exec -it calibre-web /bin/bash
> apt install python3-pip
> rerunning the dockerfile's RUN commands

### Expected Behavior

web site is acccessible

### Steps To Reproduce

fresh docker compose

### Environment

```markdown
pulled using docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
image pulled using docker compose
```

### Container logs

```bash
...
calibre-web  | ModuleNotFoundError: No module named 'flask'
calibre-web  | Traceback (most recent call last):
calibre-web  |   File "/app/calibre-web/cps.py", line 28, in <module>
calibre-web  |     from cps.main import main
calibre-web  |   File "/app/calibre-web/cps/__init__.py", line 28, in <module>
calibre-web  |     from flask import Flask
calibre-web  | ModuleNotFoundError: No module named 'flask'
calibre-web  | Traceback (most recent call last):
calibre-web  |   File "/app/calibre-web/cps.py", line 28, in <module>
calibre-web  |     from cps.main import main
calibre-web  |   File "/app/calibre-web/cps/__init__.py", line 28, in <module>
calibre-web  |     from flask import Flask
calibre-web  | ModuleNotFoundError: No module named 'flask'
calibre-web  | Traceback (most recent call last):
calibre-web  |   File "/app/calibre-web/cps.py", line 28, in <module>
calibre-web  |     from cps.main import main
calibre-web  |   File "/app/calibre-web/cps/__init__.py", line 28, in <module>
calibre-web  |     from flask import Flask
...
```

**Comment by radcki** [comment]
I had same issue. It can be fixed simply by changing "python3" to "/lsiopy/bin/python3" here: https://github.com/linuxserver/docker-calibre-web/blob/75774e65f23605d2e87ff190dbf71e21cdde76a5/root/etc/s6-overlay/s6-rc.d/svc-calibre-web/run#L8

**Comment by aptalca** [comment]
That's not a proper solution. You need to fix the env vars you're setting.

https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by radcki** [comment]
Right, as reference for others - when compared to fresh deployment I was missing "/lsiopy/bin" in PATH variable.

**Comment by aptalca** [comment]
The real solution is that you should not be setting the PATH variable at all. It's meant to be an internal var that is set in the image, not externally in compose or docker run
