### ISSUE TITLE
Port issues with container in K8S cluster

### ISSUE THREAD

**Issue by paulmorabito** [linuxserver/docker-calibre-web#33]
Hi,

I'm trying to deploy the linuxserver docker via a kubernetes cluster and I'm getting the following error:

Traceback (most recent call last):
File "/app/calibre-web/cps.py", line 13, in 
from cps.server import Server
File "/app/calibre-web/cps/server.py", line 25, in 
import web
File "/app/calibre-web/cps/web.py", line 36, in 
import ub
File "/app/calibre-web/cps/ub.py", line 64, in 
DEFAULT_PORT = int(os.environ.get("CALIBRE_PORT", 8083))
ValueError: invalid literal for int() with base 10: 'tcp://10.43.76.92:8083'
Traceback (most recent call last):
File "/app/calibre-web/cps.py", line 13, in 
from cps.server import Server
File "/app/calibre-web/cps/server.py", line 25, in 
import web
File "/app/calibre-web/cps/web.py", line 36, in 
import ub
File "/app/calibre-web/cps/ub.py", line 64, in 
DEFAULT_PORT = int(os.environ.get("CALIBRE_PORT", 8083))
ValueError: invalid literal for int() with base 10: 'tcp://10.43.76.92:8083'

Any port and it gives the same error. This is using the version pulled from the latest tag. Other linuxserver.io images work fine (Sonarr, Radarr etc.)

Any help would be very appreciated!

**Comment by CHBMB** [comment]
Might help if you posted your config as well, rather than just the resulting error message.....

**Comment by paulmorabito** [comment]
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    field.cattle.io/creatorId: user-qxrjg
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.52"],"port":30032,"protocol":"TCP","serviceName":"apps:calibreweb-nodeport","allNodes":true}]'
  creationTimestamp: 2019-02-15T07:42:55Z
  generation: 19
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-apps-calibreweb
  name: calibreweb
  namespace: apps
  resourceVersion: "1285080"
  selfLink: /apis/apps/v1beta2/namespaces/apps/deployments/calibreweb
  uid: 4e9b0a1e-30f5-11e9-bbfb-ca0bc1e06b0c
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-apps-calibreweb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-02-16T10:37:34Z
        field.cattle.io/ports: '[[{"containerPort":8083,"dnsName":"calibreweb-nodeport","kind":"NodePort","name":"8083tcp300321","protocol":"TCP","sourcePort":30032}]]'
        field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.52"],"allNodes":true,"port":30032,"protocol":"TCP","serviceId":"apps:calibreweb-nodeport"}]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-apps-calibreweb
    spec:
      containers:
      - env:
        - name: PGID
          value: "996"
        - name: PUID
          value: "1000"
        image: linuxserver/calibre-web
        imagePullPolicy: Always
        name: calibreweb
        ports:
        - containerPort: 8083
          name: 8083tcp300321
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: calibreweb-config
        - mountPath: /books
          name: calibreweb-library
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: calibreweb-config
        persistentVolumeClaim:
          claimName: calibreweb-config
      - name: calibreweb-library
        persistentVolumeClaim:
          claimName: calibreweb-library
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-02-16T10:38:14Z
    lastUpdateTime: 2019-02-16T10:38:14Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-02-16T10:42:38Z
    lastUpdateTime: 2019-02-16T10:42:38Z
    message: Deployment is paused
    reason: DeploymentPaused
    status: Unknown
    type: Progressing
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1


This is the config. 

In https://github.com/janeczku/calibre-web/issues/814 a workaround was added which may avert this. I'll test it once the docker image re-pulls from the repository.

**Comment by homerr** [comment]
Closing, issue was resolved upstream in https://github.com/janeczku/calibre-web/issues/814
