### ISSUE TITLE
Permission error while creating database?

### ISSUE THREAD

**Issue by Dinth** [linuxserver/docker-calibre-web#37]
Operating system: Debian with OpenMediaVault
Docker log:
```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2019-03-26 19:01:34,177] INFO in web: Starting Calibre Web...
[2019-03-26 19:01:34,597] INFO in server: Starting Gevent server
```

My configuration:

Calibre-web container has /Data/Ebooks mounted as /books. /Data/Ebooks/ is 2755 and root:users ownership (standard permissions in OMV, cannot really be changed).
Calibre-web container is running with PUID = 1001 (standard user account on host system) and PGID = 100 (users group on host system), but earlier i also tried running it as PUID = 0 (root account on host system) without any luck. 
When i run "docker exec -it calibre-web /bin/bash" command on the host system, i do have full read/write access to /books folder. 
But when i'm trying to set up Calibre-web client with "/books" library location, im getting the following error: "DB location is not valid, please enter correct path"

**Comment by j0nnymoe** [comment]
You need to supply an existing database in the `/books` mount for this to work.

**Comment by ha7rock** [comment]
Opreating system : Synology DS918 with Dockers

I got same error too.  And I am sure I have placed metadata.db file in /books .
any idea?

Thanks !

**Comment by CHBMB** [comment]
Check file permissions, if it's definitely there, then it will be file permissions
