### ISSUE TITLE
Uploading PDF restarts calibre-web

### ISSUE THREAD

**Issue by OzzieIsaacs** [linuxserver/docker-calibre-web#39]
Some users complained about restarting calibre-web instance during upload of pdf documents. 
janeczku/calibre-web#909 (reported by @vigri) and janeczku/calibre-web#789 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

The relevant informations are in both issues. 

I could track down the issue to a restriction/bug in imagemagick. @technosoft2000 could solve it by compiling imagemagick by himself and changing the security policyfile. 

The fix renables uploading pdf files via calibre-web

**Comment by CHBMB** [comment]
@OzzieIsaacs Sorry I missed this completely,  I need to chat to the others but I'm inclined to consider a rebase to Bionic tbh, Alpine is starting to get a bit "hacky" for Calibre-web and I think Bionic may open up some new opportunites with the Calibre binary issue as well.

**Comment by CHBMB** [comment]
Also, any chance you have a PDF known to cause the issue so I can test with a known problematic file?

**Comment by OzzieIsaacs** [comment]
As far as I understood it, every pdf causes the problem. @vigri is this right, or could you please provide a non working example to @CHBMB.

Thanks a lot

**Comment by vigri** [comment]
> every pdf causes the problem.

No, it were just a couple of PDFs. Normaly the majority I'm uploading to calibre is without any problems.

I'll try to find out which PDF caused the problem and get back to you guys.

Best regards

**Comment by CHBMB** [comment]
@vigri Thanks, I've been trying to reproduce but can't with any of the pdfs I'm trying.

**Comment by vigri** [comment]
Hello again,
I've tried to find the problematic PDF and been able to isolate two possible files. Both files were created using Adobe Acrobat DC (merging separate PDFs into one; compatibility: PDF-version 1.6 (Acrobat 7.x)).

However: None of the PDFs are now crashing the server :(
I can send you the PDF but I don't think it will help you.

The libs now used seem to be quite the same.

![calibre-2019-06-02](https://user-images.githubusercontent.com/2580723/58759775-ca917c00-852f-11e9-93d9-6fb9c058a874.png)

I guess we should close this issue and when the problem occur again, I'll get back to you.

**Comment by OzzieIsaacs** [comment]
Closing, as issue isn‘t reproducible anymore
