### ISSUE TITLE
Convert Tool Stopped Functioning

### ISSUE THREAD

**Issue by Oddiesea** [linuxserver/docker-calibre-web#44]
Convert tool seemed to work before, but now fails every time.
Have forced updated and reinitialized plugin, not sure of fix

Host UNRAID
Template:
![Screenshot_2019-07-07_21-39-17](https://user-images.githubusercontent.com/26882248/60773615-dc9ea580-a0ff-11e9-9f27-00a35d17381d.png)

Relevant log lines:
[2019-07-07 21:31:24,189] INFO in worker: Book id 83 - target format of .mobi does not exist. Moving forward with convert.
[2019-07-07 21:31:24,189] ERROR in worker: Convertertool not found

**Comment by CHBMB** [comment]
I can't reproduce this.  You haven't specified which convertor tool you're using so can't really help much.

Kindlegen is no longer recommended and as far as I know is being deprecated upstream.  
Calibre is the method to use now, but does need to be configured as per the readme.

**Path to convertertool** should be `/usr/bin/ebook-convert`
**Location of Unrar binary** should be `/usr/bin/unrar`

I just tested and converted a epub to mobi without any issues.  Have you tried a different book to ensure it's not that specific book that is causing issues?

**Comment by CHBMB** [comment]
No response from @Oddiesea and unable to reproduce, so closing this.
