### ISSUE TITLE
convert : MOBI->PDF failed

### ISSUE THREAD

**Issue by cikichen** [linuxserver/docker-calibre-web#47]
![image](https://user-images.githubusercontent.com/1478821/62206390-47bc5e80-b3c4-11e9-8c9a-41b704052a3a.png)
![image](https://user-images.githubusercontent.com/1478821/62206402-50149980-b3c4-11e9-8523-4f463b4c7625.png)

ENV:
NAS: QNAP TS 251+
QNAP ContainerStation 2.0.365
from hub.docker.com

**Comment by j0nnymoe** [comment]
We need this information aswell:

Host OS
Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings. 
Docker log output, docker log <container-name>
Mention if you're using symlinks on any of the volume mounts.

**Comment by CHBMB** [comment]
I've just converted a PDF to Mobi successfully, so this may be dependent on the pdf you are trying to convert

**Comment by CHBMB** [comment]
And to further test, I've just downloaded a pdf of The Poems of Goethe and successfully converted it to Mobi

So it must be something specific to the file you have.

**Comment by CHBMB** [comment]
You could try running this to see if it fixes the issue you're having

```
docker exec -it calibre-web bash
apt update && apt install libxcomposite1
```

**Comment by cikichen** [comment]
> I've just converted a PDF to Mobi successfully, so this may be dependent on the pdf you are trying to convert

I want to convert Mobi->PDF

**Comment by CHBMB** [comment]
Did you try my suggestion above?

**Comment by cikichen** [comment]
> You could try running this to see if it fixes the issue you're having
> 
> ```
> docker exec -it calibre-web bash
> apt update && apt install libxcomposite1
> ```

solved. Thanks.

**Comment by CHBMB** [comment]
Fixed with https://github.com/linuxserver/docker-calibre-web/commit/ece79cc0eaf5769ec9ccea2c104ef534d26c6cb8
