### ISSUE TITLE
Convert:PDF->EPUB failed

### ISSUE THREAD

**Issue by cikichen** [linuxserver/docker-calibre-web#51]
![image](https://user-images.githubusercontent.com/1478821/62774913-cc9c2c00-bad8-11e9-89f2-0606e3683e18.png)

![image](https://user-images.githubusercontent.com/1478821/62774933-de7dcf00-bad8-11e9-9922-d192ffc48b5b.png)

ENV:
NAS: QNAP TS 251+
QNAP ContainerStation 2.0.365
from hub.docker.com

**Comment by thelamer** [comment]
That looks like a rather verbose and specific Error message from the application itself. 
Do you have any reason to believe this is related to us putting this in a Docker container or do you think this question would be better suited for the upstream application ? 

https://github.com/janeczku/calibre-web
