### ISSUE TITLE
Getting "Database location invalid" during initial setup

### ISSUE THREAD

**Issue by Hello-User** [linuxserver/docker-calibre-web#52]
Using ocamlfuse for google drive mount because gdrive integration crashes the container for me

Host OS: Ubuntu 18.04.3 LTS
Using portainer.

output of `docker exec -it calibre-web ls -la /books/metadata.db`: 

-rwxr-xr-x 1 root root 663552 Oct  3 14:46 /books/metadata.db

trying to set /books as database location during initial setup 

### Logs

[cont-init.d] done.

[services.d] starting services

[services.d] done.

[2019-10-03 14:41:09,903] INFO in web: Starting Calibre Web...

[2019-10-03 14:41:10,352] INFO in server: Starting Gevent server

::ffff:10.10.0.2 - - [2019-10-03 14:41:16] "GET / HTTP/1.1" 302 392 0.011329

::ffff:10.10.0.2 - - [2019-10-03 14:41:16] "GET /config HTTP/1.1" 200 13243 0.120930

::ffff:10.10.0.2 - - [2019-10-03 14:41:39] "POST /config HTTP/1.1" 200 13775 0.076935

::ffff:10.10.0.2 - - [2019-10-03 14:44:22] "POST /config HTTP/1.1" 200 13775 0.103569

::ffff:10.10.0.2 - - [2019-10-03 14:44:28] "POST /config HTTP/1.1" 200 13775 0.104940

::ffff:10.10.0.2 - - [2019-10-03 14:45:01] "POST /config HTTP/1.1" 200 13775 0.140496

::ffff:10.10.0.2 - - [2019-10-03 14:53:11] "POST /config HTTP/1.1" 200 13775 0.078066

::ffff:10.10.0.2 - - [2019-10-03 14:53:17] "GET / HTTP/1.1" 302 392 0.006492

::ffff:10.10.0.2 - - [2019-10-03 14:53:17] "GET /config HTTP/1.1" 200 13250 0.019785

::ffff:10.10.0.2 - - [2019-10-03 14:53:21] "GET / HTTP/1.1" 302 392 0.004803

::ffff:10.10.0.2 - - [2019-10-03 14:53:21] "GET /config HTTP/1.1" 200 13250 0.020191

::ffff:10.10.0.2 - - [2019-10-03 14:53:25] "GET /admin/view HTTP/1.1" 302 392 0.005883

::ffff:10.10.0.2 - - [2019-10-03 14:53:25] "GET /config HTTP/1.1" 200 13250 0.021645

::ffff:10.10.0.2 - - [2019-10-03 14:53:30] "POST /config HTTP/1.1" 200 13775 0.106767

**Comment by aptalca** [comment]
Likely permission issue. The file is owned by root

But can't say for sure because you didn't post a full log

**Comment by Hello-User** [comment]
This is all the log I can find.

The only other thing is calibre-web.log in my config folder which just has redundant information.

[2019-10-03 14:41:09,903] {/app/calibre-web/cps/web.py:188} INFO - Starting Calibre Web...
[2019-10-03 14:41:09,936] {/app/calibre-web/cps/comic.py:32} WARNING - cannot import comicapi, extracting comic metadata will not work: No module named parse
[2019-10-03 14:41:10,352] {/app/calibre-web/cps/server.py:84} INFO - Starting Gevent server

**Comment by j0nnymoe** [comment]
What's your docker run/compose info?

**Comment by Hello-User** [comment]
I'm using portainer but this would be the equivalent command if I created the container via a command-line 

`"docker create \
  --restart unless-stopped \
  --name=calibre-web \
  -v /root/calibre-web/config:/config \
  -v /root/gdrive/calibre:/books \
 -e TZ=Europe/Amsterdam \
  -e DOCKER_MODS=linuxserver/calibre-web:calibre \
  -p 8083:8083 \
  linuxserver/calibre-web
"`

**Comment by j0nnymoe** [comment]
You need to use PUID/PGID and also not run the container as root.

**Comment by Hello-User** [comment]
setting PUID and PGID to 0(root) resolved the issue.

I know running my containers as root is a security issue but quiet frankly, seeing as this is running on a free digitalocean instance, I don't really care
