### ISSUE TITLE
No form for unrar path

### ISSUE THREAD

**Issue by Seketh** [linuxserver/docker-calibre-web#68]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Readme states the following: "Unrar is included by default and needs to be set in the Calibre-Web admin page (Basic Configuration:External Binaries) with a path of /usr/bin/unrar"

## Current Behavior
No such form exists to input the unrar path. Only options available in External Binaries are the following:
 
```
- No converter

- Use Kindlegen
 
- Use calibre's ebook converter

E-Book converter settings

Path to convertertool
```

I'm unable to read CBR files in Calibre-Web.

## Steps to Reproduce
N/A

## Environment
OS: Raspian
CPU architecture: arm32   
How docker service was installed:  docker-compose

## Command used to create docker container (run/create/compose/screenshot)
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /home/docker/calibre-web:/config
      - /media/calibre:/books
    ports:
      - 8083:8083
    restart: unless-stopped

## Docker logs
N/A

**Comment by CHBMB** [comment]
https://github.com/janeczku/calibre-web/issues/1225

**Comment by CHBMB** [comment]
Fixed in latest release
