### ISSUE TITLE
the prebuild docker image suffered from docker  cache

### ISSUE THREAD

**Issue by rockonedege** [linuxserver/docker-calibre-web#69]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

pulling the image from  the registry, the web-calibre is not the latest version on github. it seems a previous version was cached when it was  first built. 
------------------------------

## Expected Behavior

it should pull the latest version of web-calibre released from github.

## Current Behavior

it is an outdated version of web-calibre. [this article](https://thenewstack.io/understanding-the-docker-cache-for-faster-builds/) seems to explained why.
## Steps to Reproduce

1.  docker pull the image and run it
2.  log into web-calibre to open open any book, in the details pages check that reading online feature is not available, which IS a feature in latest versions of web-calibre.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
our jenkins builder does not use cache https://github.com/linuxserver/docker-calibre-web/blob/master/Jenkinsfile#L323

**Comment by aptalca** [comment]
0.6.6 is the latest calibre build and that's what we've been building since Feb. We pushed multiple builds due to OS package updates. What version were you expecting? @rockonedege

**Comment by rockonedege** [comment]
Then I was mistaken about why.

You could see the difference of calibre-web between linuxserver  and technosoft2000 docker images
![comparison](https://user-images.githubusercontent.com/717477/78630099-6c5dc400-78cb-11ea-838f-b75ca8f53fd3.jpg)

It's been sometime the 'read in browser' was with technosoft2000 . So I think linuxserver  was getting an outdated version. Now that it's not related to docker cache, I don't know why.

I am expecting the same as in technosoft2000 .

**Comment by tobbenb** [comment]
Saying you expect the same as another container without say which version doesn't help us at all.
If you don't supply the information we ask of you we will close the issue.

**Comment by rockonedege** [comment]
It's not that I did not want to provide aversion number. It's hard to find the version of calibre-web within the app.

I was trying to find out in the source code when this feature was in. No success yet.
One thing I was sure that this feature was in Technosoft before the release date of 0.66. I was considering switching to linuxserver and found it missing during the trial.
I thought it had something to do with --cache. If you are sure it's not the case, you are welcome to close it.

**Comment by CHBMB** [comment]
You checked this setting?
![screenshot](https://user-images.githubusercontent.com/3609888/79510344-1f998c00-8035-11ea-983a-c925e958b776.png)

**Comment by rockonedege** [comment]
@CHBMB Thanks, that does the trick. I am wondering how it's disabled in this distribution but enabled by default in another.

anyway, problem sovled. @aptalca I think this ticket can be closed now unless you'd like to change investigate the default settings.
