### ISSUE TITLE
Book cover could not be display, but cover.jpg had been downloaded.

### ISSUE THREAD

**Issue by 2770862886** [linuxserver/docker-calibre-web#70]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Steps to Reproduce

1. Upload a new book
2. Click Get Metadata，Book Cover displayed。
3. But after submit，it shows ”cover no available“
4. And check /books folder，cover.jpg had been downloaded。

## Environment
**OS:**  Synology 918+    
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by CHBMB** [comment]
Unable to reproduce this with some mobi and epub files I tried.

**Comment by CHBMB** [comment]
Please retest now v0.6.7 has been released.

https://github.com/janeczku/calibre-web/releases/tag/0.6.7

**Comment by CHBMB** [comment]
Closing this, not enough detail and can't reproduce and no response from @2770862886
