### ISSUE TITLE
Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

### ISSUE THREAD

**Issue by cikichen** [linuxserver/docker-calibre-web#71]
PDF.js v2.2.228 (build: d7afb74a)
Info：Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
------------------------------

**Comment by jeygith** [comment]
Also having this issue on Chrome Version 81.0.4044.92.

**Comment by CHBMB** [comment]
Not enough information to even attempt to look at unfortunately.  We have the template for a reason.  Can't reproduce, can't investigate. 

Please open a new issue with the required information
