### ISSUE TITLE
cover not avaliable

### ISSUE THREAD

**Issue by szdefine** [linuxserver/docker-calibre-web#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Current Behavior
when upload ebook by calibre-web, then get the metadata(everything 's fine ,the cover image shows too) ,submit. but the cover image is gone (no matter you upload the cover image from the local driver or get the metadata)
![image](https://user-images.githubusercontent.com/48077232/79963182-a1693980-84bb-11ea-90eb-056d1f0c310f.png)
![image](https://user-images.githubusercontent.com/48077232/79963235-b0e88280-84bb-11ea-8933-61be754be98f.png)

## Steps to Reproduce

1.upload ebook by calibre-web
2.open the book and edit
3.get the metadata 
4.submit. 
5.the book's cover image is gone

## Environment
**OS:**   docker 19.03.8
**CPU architecture:** x86_64/ Centos 7
**How docker service was installed:**      
## Command used to create docker container (run/create/compose/screenshot)
docker create \
  --name=calibre-web \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Shanghai \
  -e DOCKER_MODS=linuxserver/calibre-web:calibre \
  -p 8083:8083 \
  -v  /opt/ebook:/config \
  -v  /opt/ebook/Library:/books \
  --restart unless-stopped \
  linuxserver/calibre-web

## Docker logs

![image](https://user-images.githubusercontent.com/48077232/79963097-85fe2e80-84bb-11ea-895b-db2832d9838a.png)

**Comment by tobbenb** [comment]
I can't reproduce this here. If I upload a book and hit submit, the cover is still there.

Have you tried to hit f5 to force a refresh of the page?

**Comment by szdefine** [comment]
it's chrome's cache problem , not the container's .
