### ISSUE TITLE
Cover reading blocked by Imagemagick policy

### ISSUE THREAD

**Issue by Stew-rt** [linuxserver/docker-calibre-web#75]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

On book upload, appliance attempts to set the cover image to the cover of the PDF
## Current Behavior

Appliance fails to read cover

Logs:
`WARN {cps.uploader:159} Pdf extraction forbidden by Imagemagick policy: not authorized`

## Resolution
Referenced on calibre-web github issues [here](https://github.com/janeczku/calibre-web/issues/827#issuecomment-467578477)

Modify /etc/ImageMaick-6/policy.xml
remove:
`<policy domain="coder" rights="none" pattern="PDF" />`
add:
`<policy domain="coder" rights="read" pattern="PDF" />`

**Comment by aptalca** [comment]
It looks like it's fixed upstream but there hasn't been a new release since. When there is a new release, we'll push a new build out.

**Comment by CHBMB** [comment]
Please retest now v0.6.7 has been released.

https://github.com/janeczku/calibre-web/releases/tag/0.6.7

**Comment by a1ex4** [comment]
Using the latest build this is unfortunately not fixed by the version. Where did you see that it was fixed ?
Nothing is related to the issue or fix in the release note anyway. Thanks a lot !

**Comment by Stew-rt** [comment]
I can confirm the latest docker image (with version 0.6.7 of calibre-web) still exhibits the same issue. It can be resolved as described at the beginning of this issue.

**Comment by CHBMB** [comment]
@a1ex4 Sorry, just realised I was looking at the issue you linked to and didn't realise it was March 2019, not March 2020.

Will take a look
