### ISSUE TITLE
[feature request] Kepubify

### ISSUE THREAD

**Issue by Dinth** [linuxserver/docker-calibre-web#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
The latest version of calibre-web brings support for Kepubify tool to convert files to Kepub format.
It would be nice to include it in this docker image (in same way as the other converter is)

## Current Behavior
Kepubify tool is not included

**Comment by CHBMB** [comment]
@Dinth 

I've added kepubify to the x86-64 and arm32v7 builds.  
(I don't think there is a kepubify arm64v8 binary, but have asked the kepubify author to clarify)

Mind testing this build to check the conversion is working for you?

`lsiodev/calibre-web:0.6.8-pkg-86d40a58-dev-560d7457497af8a29d8f4ed066572de5b01b8562`

Instructions to set the appropriate path to the binary are [here](https://github.com/linuxserver/docker-calibre-web/blob/kepubify/readme-vars.yml#L59)

Set the path for epubify to `/usr/bin/kepubify`

Relevant upstream issues:
https://github.com/janeczku/calibre-web/issues/1132
https://github.com/janeczku/calibre-web/pull/1014

Once you've tested and confirmed it's working, and I am 100% certain whether the kepubify arm binary produced is 32 or 64 bit (I'm like 98% certain it will be 32 bit) then I can get this merged to master.

**Comment by Dinth** [comment]
Hey. While i cannot test actual validity of produced kepubs at the moment, the converting works for me and im getting modified files with kepub extension.
