### ISSUE TITLE
Kepubify for aarch64

### ISSUE THREAD

**Issue by CHBMB** [linuxserver/docker-calibre-web#81]
Currently no upstream binary, however the dev is going to produce one for the next release.  Once that's done can add kepubify to the 64bit aarch image. 

(Will potentially need to change the name of the arm32 kepubify binary - remember to check)

**Comment by geek1011** [comment]
This has been released in v3.1.3.

**Comment by CHBMB** [comment]
@geek1011 Thanks for the headsup, I was checking in every so often!
