### ISSUE TITLE
port missing from 'container info' on fleet

### ISSUE THREAD

**Issue by IronicBadger** [linuxserver/docker-calibre-web#83]
port info missing from 'container info' on fleet

<img width="637" alt="image" src="https://user-images.githubusercontent.com/2773080/83959334-ae62a200-a849-11ea-9b18-f9a7652680cc.png">

**Comment by JoshStark** [comment]
Thanks for the reminder. That data is manually administered in Fleet so we’ll try to find some time as soon as possible to get all that filled in (it’ll take a while!).

**Comment by CHBMB** [comment]
I've done it
