### ISSUE TITLE
Tornado reverse proxy issue

### ISSUE THREAD

**Issue by douglasak** [linuxserver/docker-calibre-web#84]
Also reported in https://github.com/janeczku/calibre-web/issues/1477

Describe the bug/problem
I'm having an issue with version 0.6.8 in the LinuxServer docker. Version 0.6.7 works fine. The issue occurs when accessing Calibre-Web through an SSL reverse proxy. The error message shows up in the log below and Nginx reports "502 Bad Gateway".

Calibre-Web works fine when accessing directly outside the reverse proxy.

To Reproduce
Access webpage through SSL reverse proxy.

Logfile
Add content of calibre-web.log file or the relevant error, try to reproduce your problem with "debug" log-level to get more output.

[2020-06-08 14:26:07,040] ERROR {tornado.application:67} Uncaught exception
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/tornado/http1connection.py", line 273, in _read_message
delegate.finish()
File "/usr/local/lib/python3.6/dist-packages/tornado/httpserver.py", line 280, in finish
self.request_callback(self.request)
File "/usr/local/lib/python3.6/dist-packages/tornado/wsgi.py", line 114, in call
WSGIContainer.environ(request), start_response
File "/usr/local/lib/python3.6/dist-packages/tornado/wsgi.py", line 154, in environ
port = int(hostport[1])
ValueError: invalid literal for int() with base 10: '443,calibre.internaldomain.net

Expected behavior
Calibre-Web should load correctly through the reverse proxy.

Screenshots
N/A

Environment (please complete the following information):

OS: Docker
Python version: Python 3.6
Calibre-Web version: 0.6.8 not 0.6.7
Docker container: LinuxServer 0.6.8-ls66 and 0.6.8ls65 but not 0.6.7-ls64
Additional context
Access via reverse proxy

**Comment by tobbenb** [comment]
I assume you are using our letsencrypt container for reverse proxy? If you are, can you delete the proxy.conf in /config/nginx and restart the letsencrypt container and see if that fixes it?

**Comment by douglasak** [comment]
Yes, thank you!
