### ISSUE TITLE
Attempting to download PDF boots you back to login page

### ISSUE THREAD

**Issue by zkhcohen** [linuxserver/docker-calibre-web#85]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Clicking on Download PDF in book details causes calibre-web to boot you back to the login screen.

This issue does not occur for other formats. Viewing PDFs works as expected, and they can be downloaded from the viewer (once fully cached).

------------------------------

## Expected Behavior
The PDF should download.

## Current Behavior
You get booted back to the login screen.

## Steps to Reproduce

1. Navigate to a PDF.
2. Open book details by clicking on the cover.
3. Select the PDF download (blue) button.
4. You are redirected to <URL>/login?next=%2Fdownload%2F1150%2Fpdf%2F1150.pdf

## Environment
**OS:**      RancherOS via ProxMox with OMV CIFS share for Calibre Library and configuration.
**CPU architecture:** x86_64    
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
version: "**3.5**"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    networks:
      - containers
    environment:
      - PUID=1100
      - PGID=1101
      - UMASK_SET=022
      - TZ=america/los_angeles
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
        - ../share/calibre-web/config:/config
        - ../../../calibre_storage/books:/books
    restart: unless-stopped
networks:
  containers:
    external: true

## Docker logs

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1100
User gid:    1101
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 60-calibre-config: executing... 
[cont-init.d] 60-calibre-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

**Web logs:**

[2020-06-08 21:47:13,434]  INFO {cps:98} Starting Calibre Web...
[2020-06-08 21:47:13,524]  INFO {cps.server:156} Starting Tornado server on :8083

**Comment by zkhcohen** [comment]
Oddly enough, roughly 1:3 times I click on Advanced Search, I also get booted back to the login page...

I have completely rebuilt the container, deleting all persistent data, and the issue persists.

**Comment by CHBMB** [comment]
I can't reproduce this, I don't use pdfs in my library but just added one and downloaded it multiple times uneventfully.  

Is your calibre-web behind a reverse proxy (mine is using nginx), I'm guessing you are as there's no mapped ports in your docker-compose and fwiw I'm using a local folder for my `/books` mount, rather than a CIFS mount, so I think it's probably one of those causing the issue.

Can you try accessing calibre-web from `http://$HOST_IP-ADDRESS:$MAPPED_HOST_PORT`

**Comment by CHBMB** [comment]
My gut feeling is it's the CIFS mount tbh

**Comment by zkhcohen** [comment]
> Is your calibre-web behind a reverse proxy (mine is using nginx), I'm guessing you are as there's no mapped ports in your docker-compose 

Great guess -- I use Traefik.

> Can you try accessing calibre-web from `http://$HOST_IP-ADDRESS:$MAPPED_HOST_PORT`

...annd it worked.

What in the world is different about PDF downloads _**specifically**_ (and using a reverse proxy) that would cause this to occur?

**Comment by CHBMB** [comment]
No idea matey, never laid a hand on Traefik.  But at least it gives some direction.  I can't really help unfortunately as it's not an issue I can sort out from the docker image side.

If you do figure it out, would you mind posting a solution so any other Traefik users can see.

Hopefully someone might happen across this issue and lend a hand.

**Comment by zkhcohen** [comment]
Session security was hardened on calibre-web on May 9th, which appears to be causing the problem:

https://github.com/janeczku/calibre-web/issues/1466#issuecomment-639057441

I'm going to try this fix ASAP and report back before closing the issue.

**Comment by CHBMB** [comment]
@zkhcohen Our image automatically rebuilds on any new releases and weekly to update any other packages in the image.
