### ISSUE TITLE
not able to setup calibre server

### ISSUE THREAD

**Issue by krishnasen2401** [linuxserver/docker-calibre-web#86]
the page doesnt move forward the library location page

`root@DietPi:~# docker exec -it Calibreweb ls -la /books/metadata.db
-rw-r--r-- 1 root root 2 Jun 17 13:19 /books/metadata.db
failed to resize tty, using default size`

when it try to enter \books in the field it gives me this error

![image](https://user-images.githubusercontent.com/13378434/84904056-80dcea80-b0cc-11ea-9448-78b26cce5fef.png)

**Comment by CHBMB** [comment]
Try `/books`

**Comment by krishnasen2401** [comment]
Already tried change file permissions everything nothing works

**Comment by CHBMB** [comment]
I'll leave this closed as to be honest you need to fill in the issue template so we can look at it, rather than delete it and write three lines and a screenshot.

Want to open a new issue and fill in the required info and we can look at it then.
