### ISSUE TITLE
Try `/books`

### ISSUE THREAD

**Issue by krishnasen2401** [linuxserver/docker-calibre-web#87]
Try `/books`

_Originally posted by @CHBMB in https://github.com/linuxserver/docker-calibre-web/issues/86#issuecomment-645394271_

Already tried change file permissions everything nothing works

So kindly open the issue I had posted after checking the puid pgid to 0 chmod777 everything from previous issues

I have installed via portainer

**Comment by CHBMB** [comment]
Fill in the template or I will keep closing these issues.
