### ISSUE TITLE
feat: support for grabbing latest from master

### ISSUE THREAD

**Issue by jef** [linuxserver/docker-calibre-web#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

It'd be nice to have multiple versions to grab from calibre-web.

------------------------------

## Expected Behavior

Adding a Docker tag of `nightly` like [`beets`](https://hub.docker.com/r/linuxserver/beets) would be beneficial as releases don't happen as often as other services (Sonarr, Radarr, etc).

## Current Behavior

Only includes latest release.

**Comment by jef** [comment]
I believe this can be solved by using `CALIBREWEB_RELEASE` to `master`. Maybe should just update the doc to include this unless it's somewhere else that specifies this configuration?

**Comment by aptalca** [comment]
if you're just troubleshooting, you can build it locally and pass the docker arg. Instructions are in the readme: https://github.com/linuxserver/docker-calibre-web#building-locally

Before we decide to publish a new tag, we'd have to take into consideration various things like how much interest there is for building master commits, how stable they are, how frequent they are, etc.

**Comment by jef** [comment]
[Releases seem to vary](https://github.com/janeczku/calibre-web/releases). Most things pushed to master are fixes rather than features it seems. I'll build locally for now and go from there.
