### ISSUE TITLE
Book conversion on raspberry pi?

### ISSUE THREAD

**Issue by HarvsG** [linuxserver/docker-calibre-web#93]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

I would like to be able to convert books on my ARM instance of calibre-web
## Current Behavior

There is no ability to convert books using pandoc or similar
## Steps to Reproduce

1. Deploy this image on an arm device

## Environment
**OS:Raspberry Pi OS**      
**CPU architecture:** arm64      
**How docker service was installed: ** Linuxserver.io template on portainer

**Comment by aptalca** [comment]
There is no published calibre binary for armhf or arm64

**Comment by HarvsG** [comment]
Would it be possible to implement a different binary like pandoc? I have noticed that support has been added for kpubify in recent builds

**Comment by j0nnymoe** [comment]
You can add it yourself to our containers via https://blog.linuxserver.io/2019/09/14/customizing-our-containers/ :)

**Comment by CHBMB** [comment]
@HarvsG To implement more book conversion methods you'd need to talk to upstream

**Comment by CHBMB** [comment]
To summarise.

1. Kepubify produces the binaries, so no issue there.
2. As I mentioned before, pandoc or any other solution needs to be discussed upstream, not here.
3.  Calibre is possible to install on arm/aarch by utilising a customisation of our container, like @j0nnymoe linked to.
```
#!/bin/bash
sudo apt update
sudo apt install calibre
```
The main issue with this is it installs a **ton** of cruft that we don't need and will only install the version of calibre that is included in the Ubuntu repos (Currently v3.21) rather than the current version that is available (v4.21 with a beta v5 recently released)

Raspbian or any other distro you might run on your Pi (or other SoC) is immaterial as you're installing inside the container, which is Ubuntu based so what you've suggested @Snack32 won't work, as that will install Calibre on the host system.  I guess if you map the binary in, it *might* work, but it's hacky at best and if it needs a dependency (which iirc, it does, then it won't work.

**Comment by Snack32** [comment]
Apologies for the delayed response.

I've been testing about it and there are good news and bad news.

Good news: Installing Calibre (arm version) via console inside Calibre-web, the ebook-convert works flawless (And in the “About” section it is shown as perfectly installed).

Bad news: These method is a bit overkill, because installs the full calibre as noted by @CHBMB  . 

Noting that, would it be possible to modify the docker mod to pull the arm version of Calibre and install only the essential libraries to work? (Same as it works in x86-64) It would involve touching only a couple of lines or… involve something much more cumbersome?

Thanks in advance!

<img width="844" alt="calibrestats" src="https://i.imgur.com/77FdeUe.jpg">

**Comment by fivestones** [comment]
I'm pretty interested in this too. Does anyone know how complicated it would be to get the docker image on arm to pull the arm version of calibre and then only install the essential libraries to do ebook converstion?

**Comment by CHBMB** [comment]
@fivestones To be honest, I wouldn't even want to try and sort that out.  I think realistically that we need to accept that non-x64 architectures come with some limitations here.

The only realistic way I can see this being implemented is the solution I posted previously.  The downside being that you're limited to the Calibre version in whichever repository we're using for this container.  For the purposes of on the fly book conversion I would suspect that is largely irrelevant though.

**Comment by jwillmer** [comment]
if I interpret this thread correctly then it means that having the converter running inside a pi docker image is possible. So would someone with some insights in "how" be kind enough and offer us such a solution. I guess I'm not alone in saying that this would be highly appreciated 😃

**Comment by mmguero** [comment]
I've got a project that runs in Docker on raspberry pi and uses ebook-convert.

[Here's my Dockerfile](https://github.com/mmguero/montag/blob/master/Dockerfile.arm32v7#L1-L77). Just ignore the last few lines where I add my own script and you end up with an ubuntu-based docker image with ebook-convert, etc. that should work.

**Comment by gsp8181** [comment]
I have a project that just adds in calibre over the linuxserver image, with weekly armhf/arm64 builds. It's a bit big but works fine for raspberry pi or oracle cloud projects
https://hub.docker.com/repository/docker/gsp8181/calibre-web

**Comment by gsp8181** [comment]
@mmguero Does that file add in all the UI dependencies? how big is final image?

**Comment by mmguero** [comment]
No, it doesn't add in all the UI dependencies. Some, like xvfb and a few of its dependencies are necessary. I apt-get install calibre-bin and then apt-download calibre and dpkg --force-all -i that package and then manually rm -rf some unnecessary stuff.

https://github.com/mmguero/montag/blob/master/Dockerfile.arm32v7#L74-L76

On arm it ends up being about 400MB. My full calibre-web image comes out about 800 MB.

**Comment by jwillmer** [comment]
@gsp8181 can we see the Dockerfile for your image? Maybe linuxserver can incorporate it / offer it as `plugin`?

**Comment by gsp8181** [comment]
@mmguero I built it over your dockerfile and it seems to work great thanks! added it to my autobuild under the experimental tag and will give it some testing over my calibre-web. Doesn't remove any of the dependencies used in the linuxserver image. 

@jwillmer The experimental tag is https://gist.github.com/gsp8181/c80491c884add7d3184509ce162e8879 and the latest tag is the very basic
```
FROM ghcr.io/linuxserver/calibre-web
RUN apt-get update && apt-get install -y calibre
```

**Comment by mmguero** [comment]
Great, that is the basis of what I use for my [calibre-web dockerfile for arm](https://github.com/mmguero/docker/blob/master/services/calibre-web/docker/Dockerfile.arm32v7) as well so I hope it works out for yours. Cheers.

**Comment by pgaskin** [comment]
Kepubify v4 now has arm64 builds, and is also another 3-6 times faster than v3.

**Comment by jwillmer** [comment]
I searched for Kepubify and it only supports epub to Lobo so it is not a good replacement.

**Comment by pgaskin** [comment]
I was mentioning this here primarily about the embedded kepubify in calibre-web (for lack of a better place) than for the specific issue being discussed. I thought this issue would be more suitable than https://github.com/janeczku/calibre-web/issues/1439 since this one's about conversion on arm64.

**Comment by CHBMB** [comment]
@pgaskin Hi Patrick, yeah kepublify gets updated automatically.  Appreciate your work on that!

**Comment by CHBMB** [comment]
@mmguero @gsp8181 

I don't have ARM hardware to test.  But have you tried just simply this https://github.com/linuxserver/docker-calibre-web/issues/93#issuecomment-661272327

I'd be interested to know what size benefits you get with your dockerfile over just the above.

**Comment by gsp8181** [comment]
> I don't have ARM hardware to test.  But have you tried just simply this https://github.com/linuxserver/docker-calibre-web/issues/93#issuecomment-661272327

Yep that's the method I used to use and that works fine but installs a ton of chaff as mentioned, tons of GUI stuff.

> I'd be interested to know what size benefits you get with your dockerfile over just the above.

550MB compressed using the simple apt install calibre vs 250MB compressed using that dockerfile

**Comment by gsp8181** [comment]
@CHBMB 

Oracle provides 4x Amphere arm64 instances for free with their always free tier which can be combined to a single instance.

**Comment by CHBMB** [comment]
@gsp8181 That's pretty impressive.  Lemme talk to the fellas, any interest in maintaining this and we can build on our hardware?  Would need some readme changes etc and a PR.

**Comment by pgaskin** [comment]
Note that the Ampere instances have to be recreated after the initial full trial period expires for new accounts.

**Comment by jwillmer** [comment]
could we put this on a feature request pipeline? give it more visibility?

**Comment by emailforos** [comment]
You can use https://hub.docker.com/r/y484v/calibre based in linuxserver/calibre-web and it has in addition the ebook convert

**Comment by kfstorm** [comment]
Hi, Everyone.

Just another solution for you to try if you found the methods above don't work or don't suit your needs.

linuxserver/calibre recently started releasing arm images according to https://github.com/linuxserver/docker-calibre/issues/32#issuecomment-1016107766. So what I'm thinking is that instead of putting calibre binary files into the calibre-web image, which may result in broken dependencies or out-of-date binaries, I'm trying to run ebook-convert from another docker container.

The basic idea is to create a script called `ebook-convert` and put it to `/usr/bin/`. In this script, `docker run` will be invoked. With the correct volume mounting, this works like a charm! 🎉

Content of Dockerfile:

```dockerfile
FROM linuxserver/calibre-web

RUN curl -sSL https://get.docker.com/ | sh

COPY ebook-convert /usr/bin/
```

Content of ebook-convert (remember to invoke `chmod +x`):

```bash
#!/bin/bash

docker run --rm --entrypoint ebook-convert -v <MEDIA_FOLDER_ON_HOST>:<MEDIA_FOLDER_IN_CONTAINER> linuxserver/calibre:arch "$@"
```

Create a folder named `calibre-web` along with `docker-compose.yml` and put files into the sub-folder.

At last, replace `image: linuxserver/calibre-web` with `build: ./calibre-web` add volume `/var/run/docker.sock:/var/run/docker.sock` in your docker-compose.yml for the `calibre-web` container.

Run `docker-compose up -d --remove-orphans --build` to restart the calibre-web container.

**Comment by kfstorm** [comment]
Follow up on the previous reply.

Watchtower cannot rebuild the customized Dockerfile once the upstream image is updated. So I ended up with the startup script feature of linuxserver images.

docker-compose.yaml:

```yaml
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    volumes:
      - ./calibre-web/install-docker.sh:/config/custom-cont-init.d/install-docker.sh
      - ./calibre-web/ebook-convert:/usr/bin/ebook-convert
      - /var/run/docker.sock:/var/run/docker.sock
      - ...
    restart: unless-stopped
```

calibre-web/install-docker.sh:

```bash
#!/bin/bash

if ! command -v docker > /dev/null; then
    curl -sSL https://get.docker.com/ | sh
fi
```

calibre-web/ebook-convert:

```bash
#!/bin/bash

docker run --rm --entrypoint ebook-convert -v /root/data/mediacenter/media:/media linuxserver/calibre:arch "$@"
```

**Comment by HarvsG** [comment]
> I have a project that just adds in calibre over the linuxserver image, with weekly armhf/arm64 builds. It's a bit big but works fine for raspberry pi or oracle cloud projects. Ebook-convert works perfectly fine for me https://hub.docker.com/repository/docker/gsp8181/calibre-web

Installed your `:latest` in place of the old linux one but don't see any UI buttons to convert. What am I missing?

**Comment by arkharim** [comment]
Docker conversion ebook mod now support arm64.  See https://github.com/linuxserver/docker-mods/pull/402

So techincally now we can use DOCKER_MODS=linuxserver/mods:universal-calibre on arm64 (like raspberry pi4) and x86-64 images. The only not compatible is armhf.

But it doesn't work. I found a suspicious line in docker logs:
/etc/cont-init.d/98-calibre: line 30: /app/calibre/calibre_postinstall: cannot execute binary file: Exec format error
 
Has anyone the same error?

**Comment by thespad** [comment]
Can you post the output of `docker exec calibre-web uname -m`

**Comment by arkharim** [comment]
The output is: 
![imagen](https://user-images.githubusercontent.com/72758421/184293434-232a536c-2a94-4b41-a8db-cd23877cd5f1.png)

And the docker compose file is:
calibre-web:
![imagen](https://user-images.githubusercontent.com/72758421/184293814-d9fb588a-9abd-41b2-a039-299cc4b4f370.png)

It helps?

**Comment by thespad** [comment]
Ah, you're using the old mod. If you check your container logs or the [mod readme](https://github.com/linuxserver/docker-calibre-web/blob/calibre/README.md) you should see the notice - that mod never got updated to support arm64.

The live mod is https://github.com/linuxserver/docker-mods/tree/universal-calibre

**Comment by arkharim** [comment]
> Ah, you're using the old mod. If you check your container logs or the [mod readme](https://github.com/linuxserver/docker-calibre-web/blob/calibre/README.md) you should see the notice - that mod never got updated to support arm64.
> 
> The live mod is https://github.com/linuxserver/docker-mods/tree/universal-calibre

Thanks, it works!

**Comment by jwillmer** [comment]
@arkharim Do I have to set some paths in the docker UI config to make it work?

**Comment by arkharim** [comment]
I don't understand your question. I don't edit anything special in docker, only the docker mod. My current docker is like the image I post above but with the new mod reference. 

To work, you need to configure de calibre-web, go to admin section -> basic configuration -> external binaries.

You only need to put the path to eBook converter. /usr/bin/ebook-convert. 
![Screenshot_20220820-081750_Firefox](https://user-images.githubusercontent.com/72758421/185731891-1ec4baee-8aa2-41e4-b078-3dafb474a244.png)

**Comment by jwillmer** [comment]
@arkharim yes, the config you show me is what I was missing. Do I also have to set kupubify or is this another mod?

**Comment by arkharim** [comment]
I don't konw, I put all because it was possible and it was explained in the container readme.

Can you share log errors?

**Comment by mmguero** [comment]
I know this is an old issue, but thought I'd comment as I just updated my docker image (`ghcr.io/mmguero/calibre-web:latest`) based on `linuxserver/calibre-web:latest` that includes ebook-convert, working on Raspberry Pi 4 (arm64) and amd64, in case anyone ever comes here looking for something else that works.

Here's my [Dockerfile](https://github.com/mmguero/docker/blob/master/calibre-web/Dockerfile).

**Comment by arkharim** [comment]
Hi, @mmguero,
You don't need anymore this image. "Normal" calibre now supports arm64 so you can use the mod directly. In the enviroment part you need to add the mod:
 - DOCKER_MODS=linuxserver/mods:universal-calibre

**Comment by mmguero** [comment]
Thank you for informing me!

**Comment by MrCaringi** [comment]
> Hi, @mmguero, You don't need anymore this image. "Normal" calibre now supports arm64 so you can use the mod directly. In the enviroment part you need to add the mod:
> 
>     * DOCKER_MODS=linuxserver/mods:universal-calibre

it works on ARM64 architecture!

Thanks!
