### ISSUE TITLE
jsonschema missing in 6.8.0-ls77

### ISSUE THREAD

**Issue by thetvguru** [linuxserver/docker-calibre-web#96]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
jsonschema is required for kobo sync in calibre-web

## Current Behavior
jsonschema does not appear to be present in 6.8.0-ls77 but is till there in 6.8.0-ls76

## Steps to Reproduce
update to latest container.

## Environment
**OS:** Unraid      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      
Unraid community applications

**Comment by CHBMB** [comment]
The build messed up some of the python packages, although wasn't reflected particularly well in the logs and the webui would load so it passed our CI tests.  Have rebuilt and pushed a new image and it's fixed.
