### ISSUE TITLE
New version calibre-web

### ISSUE THREAD

**Issue by yeraycito** [linuxserver/docker-calibre-web#99]
https://github.com/janeczku/calibre-web/releases/tag/0.6.9

**Comment by jef** [comment]
This automatically gets bumped to latest. No need to make an issue. The ci bot will update soon.

**Comment by jef** [comment]
You can see it's already been released 2 hours ago.

https://github.com/linuxserver/docker-calibre-web/packages/49016?version=0.6.9-ls81
